cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/../tools/package_compiled_fragment_evidence.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_fixture.cmake")
if(NOT DEFINED LUNA_COMPILED_EVIDENCE_TEST_ROOT)
    message(FATAL_ERROR "synthetic evidence test requires a build-tree root")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
get_filename_component(root "${LUNA_COMPILED_EVIDENCE_TEST_ROOT}/session-${nonce}" ABSOLUTE)
if(EXISTS "${root}")
    message(FATAL_ERROR "synthetic evidence directory already exists")
endif()

function(export_fixture directory cycles eol)
    luna_compiled_bundle_fixture("${directory}/bundle" "${cycles}" "${eol}")
    set(LUNA_COMPILED_EVIDENCE_BUNDLE_DIR "${directory}/bundle")
    set(LUNA_COMPILED_EVIDENCE_OUTPUT_DIR "${directory}/evidence")
    string(REPEAT a 40 LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT)
    file(SHA256 "${directory}/bundle/manifest.csv" LUNA_COMPILED_EVIDENCE_EXPECTED_MANIFEST_SHA256)
    file(GLOB files "${directory}/bundle/*")
    set(before "")
    foreach(path IN LISTS files)
        file(SHA256 "${path}" hash)
        string(APPEND before "${path}:${hash}\n")
    endforeach()
    luna_package_compiled_evidence()
    set(after "")
    foreach(path IN LISTS files)
        file(SHA256 "${path}" hash)
        string(APPEND after "${path}:${hash}\n")
    endforeach()
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "evidence export modified input observation bytes")
    endif()
endfunction()

if(DEFINED EVIDENCE_TEST_CASE)
    if(EVIDENCE_TEST_CASE MATCHES "^(existing_output|nested_output|missing_parent|missing_anchor|wrong_anchor|bad_input)$")
        luna_compiled_bundle_fixture("${root}/bundle" 1)
        set(LUNA_COMPILED_EVIDENCE_BUNDLE_DIR "${root}/bundle")
        set(LUNA_COMPILED_EVIDENCE_OUTPUT_DIR "${root}/evidence")
        string(REPEAT a 40 LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT)
        file(SHA256 "${root}/bundle/manifest.csv" LUNA_COMPILED_EVIDENCE_EXPECTED_MANIFEST_SHA256)
        if(EVIDENCE_TEST_CASE STREQUAL existing_output)
            file(MAKE_DIRECTORY "${root}/evidence")
            file(WRITE "${root}/evidence/sentinel" "retained\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL nested_output)
            set(LUNA_COMPILED_EVIDENCE_OUTPUT_DIR "${root}/bundle/nested")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_parent)
            set(LUNA_COMPILED_EVIDENCE_OUTPUT_DIR "${root}/absent/evidence")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_anchor)
            unset(LUNA_COMPILED_EVIDENCE_EXPECTED_MANIFEST_SHA256)
        elseif(EVIDENCE_TEST_CASE STREQUAL wrong_anchor)
            string(REPEAT b 64 LUNA_COMPILED_EVIDENCE_EXPECTED_MANIFEST_SHA256)
        elseif(EVIDENCE_TEST_CASE STREQUAL bad_input)
            file(APPEND "${root}/bundle/process-1-O0.csv" "# changed\n")
        endif()
        luna_package_compiled_evidence()
    else()
        export_fixture("${root}" 1 LF)
        set(directory "${root}/evidence")
        file(READ "${directory}/evidence.csv" index)
        if(EVIDENCE_TEST_CASE STREQUAL source_hash)
            file(APPEND "${directory}/source/tests/compiled_fragment_bundle.cmake" "# changed\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL record_hash)
            file(APPEND "${directory}/bundle/process-1-O0.csv" "# changed\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_record)
            file(RENAME "${directory}/bundle/process-1-O0.csv" "${root}/retained-record.csv")
        elseif(EVIDENCE_TEST_CASE STREQUAL symlink_record)
            file(RENAME "${directory}/bundle/process-1-O0.csv" "${root}/retained-record.csv")
            file(CREATE_LINK "${root}/retained-record.csv" "${directory}/bundle/process-1-O0.csv" SYMBOLIC)
        elseif(EVIDENCE_TEST_CASE STREQUAL path_escape)
            string(REPLACE "bundle/manifest.csv," "../bundle/manifest.csv," index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL duplicate_row)
            string(APPEND index "bundle/manifest.csv,aaaaaaaa\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_row)
            string(REGEX REPLACE "bundle/manifest.csv,[0-9a-f]+\n" "" index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL duplicate_metadata)
            string(APPEND index "# approval=none\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL approval_claim)
            string(REPLACE "approval=none" "approval=approved" index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL manifest_anchor)
            string(REPEAT b 64 hash)
            string(REGEX REPLACE "(# bundle_manifest_sha256=)[0-9a-f]+" "\\1${hash}" index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL bundle_commit)
            string(REPEAT b 40 commit)
            string(REGEX REPLACE "(# bundle_git_commit=)[0-9a-f]+" "\\1${commit}" index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL semicolon)
            string(APPEND index ";\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL extra_file)
            file(WRITE "${directory}/source/unlisted.txt" "synthetic\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL expected_index)
            string(REPEAT b 64 LUNA_COMPILED_EVIDENCE_EXPECTED_INDEX_SHA256)
        elseif(EVIDENCE_TEST_CASE STREQUAL expected_commit)
            string(REPEAT b 40 LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT)
        else()
            message(FATAL_ERROR "unknown synthetic evidence rejection")
        endif()
        file(WRITE "${directory}/evidence.csv" "${index}")
        luna_verify_compiled_evidence("${directory}")
    endif()
    message(FATAL_ERROR "invalid evidence fixture was accepted")
endif()

foreach(configuration IN ITEMS "1/LF" "1/CRLF" "2/LF" "10/LF")
    string(REPLACE "/" ";" fields "${configuration}")
    list(GET fields 0 cycles)
    list(GET fields 1 eol)
    export_fixture("${root}/${cycles}-${eol}" "${cycles}" "${eol}")
endforeach()
# Migrate by copying, not moving/deleting an observation. Verify with trusted
# checkout code, then run only the known exact-byte copy of our own reader.
file(COPY "${root}/1-LF/evidence" DESTINATION "${root}/relocated")
set(directory "${root}/relocated/evidence")
file(SHA256 "${directory}/evidence.csv" LUNA_COMPILED_EVIDENCE_EXPECTED_INDEX_SHA256)
string(REPEAT a 40 LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT)
luna_verify_compiled_evidence("${directory}")
execute_process(COMMAND "${CMAKE_COMMAND}" -Werror=dev
        "-DLUNA_COMPILED_BUNDLE_DIR=${directory}/bundle"
        "-DLUNA_COMPILED_BUNDLE_EXPECTED_COMMIT=${LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT}"
        -P "${directory}/source/tests/compiled_fragment_bundle.cmake"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 0 OR NOT errors STREQUAL "")
    message(FATAL_ERROR "trusted copied reader failed after relocation: ${output}${errors}")
endif()
# A rehashed archived script is data to the byte verifier, not executable code.
unset(LUNA_COMPILED_EVIDENCE_EXPECTED_INDEX_SHA256)
file(WRITE "${directory}/source/tests/compiled_fragment_bundle.cmake"
    "message(FATAL_ERROR \"ARCHIVED_CODE_EXECUTED\")\n")
file(SHA256 "${directory}/source/tests/compiled_fragment_bundle.cmake" hash)
file(READ "${directory}/evidence.csv" index)
string(REGEX REPLACE "(source/tests/compiled_fragment_bundle[.]cmake,)[0-9a-f]+" "\\1${hash}" index "${index}")
file(WRITE "${directory}/evidence.csv" "${index}")
file(SHA256 "${directory}/evidence.csv" before)
luna_verify_compiled_evidence("${directory}")
file(SHA256 "${directory}/evidence.csv" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "evidence byte verifier modified index")
endif()
set(rejections "existing_output|already exists" "nested_output|inside the input"
    "missing_parent|output parent" "missing_anchor|requires EXPECTED_MANIFEST"
    "wrong_anchor|expected manifest SHA-256 mismatch" "bad_input|raw-file SHA-256"
    "source_hash|file SHA-256" "record_hash|file SHA-256" "missing_record|non-symlink file"
    "path_escape|noncanonical path" "duplicate_row|invalid checksum row"
    "missing_row|noncanonical path" "duplicate_metadata|exactly once"
    "approval_claim|approval claim" "manifest_anchor|manifest anchor mismatch"
    "bundle_commit|bundle metadata anchor mismatch"
    "semicolon|semicolon" "extra_file|unlisted" "expected_index|expected index SHA-256"
    "expected_commit|expected commit mismatch")
if(UNIX)
    list(APPEND rejections "symlink_record|non-symlink file")
endif()
foreach(test IN LISTS rejections)
    string(REPLACE "|" ";" fields "${test}")
    list(GET fields 0 name)
    list(GET fields 1 expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -Werror=dev "-DEVIDENCE_TEST_CASE=${name}"
            "-DLUNA_COMPILED_EVIDENCE_TEST_ROOT=${root}/children-${name}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT status EQUAL 1 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "synthetic evidence rejection ${name} failed (${status}): ${output}${errors}")
    endif()
    file(GLOB sentinel "${root}/children-existing_output/session-*/evidence/sentinel")
    foreach(path IN LISTS sentinel)
        file(READ "${path}" retained)
        if(NOT retained STREQUAL "retained\n")
            message(FATAL_ERROR "existing output sentinel was overwritten")
        endif()
    endforeach()
endforeach()
message(STATUS "Compiled Fragment evidence tests: synthetic files, relocation, archived code inert; no timing executable")
