cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_protocol.cmake")

if(NOT DEFINED LUNA_COMPILED_PROBE_EXECUTABLE OR NOT DEFINED LUNA_COMPILED_SERIES_OUTPUT_DIR OR
   LUNA_COMPILED_SERIES_OUTPUT_DIR STREQUAL "")
    message(FATAL_ERROR "compiled series requires an executable and a fresh output directory")
endif()
if(NOT DEFINED LUNA_COMPILED_PROBE_ITERATIONS)
    set(LUNA_COMPILED_PROBE_ITERATIONS 3)
endif()
if(NOT LUNA_COMPILED_PROBE_ITERATIONS MATCHES "^[1-9][0-9]*$" OR
   LUNA_COMPILED_PROBE_ITERATIONS LESS 1 OR LUNA_COMPILED_PROBE_ITERATIONS GREATER 10000000)
    message(FATAL_ERROR "compiled series iterations must be 1..10000000")
endif()
if(NOT DEFINED LUNA_COMPILED_SERIES_CYCLES)
    set(LUNA_COMPILED_SERIES_CYCLES 1)
endif()
luna_compiled_series_schedule("${LUNA_COMPILED_SERIES_CYCLES}" schedule)
luna_validate_compiled_series_schedule("${schedule}" "${LUNA_COMPILED_SERIES_CYCLES}")
file(SHA256 "${CMAKE_CURRENT_LIST_FILE}" runner_hash)
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_protocol.cmake" validator_hash)
get_filename_component(output_dir "${LUNA_COMPILED_SERIES_OUTPUT_DIR}" ABSOLUTE)
if(EXISTS "${output_dir}")
    message(FATAL_ERROR "compiled series output directory already exists; observations are never overwritten")
endif()
set(process 0)
set(combined "process,cycle,block,profile_position,profile,round,position,case,ns_per_op,calls,checksum\n")
foreach(item IN LISTS schedule)
    string(REPLACE "," ";" fields "${item}")
    list(GET fields 0 cycle)
    list(GET fields 1 block)
    list(GET fields 2 position)
    list(GET fields 3 profile)
    math(EXPR process "${process} + 1")
    # No smoke/default/invalid-CLI subprocesses interleave the measured series.
    execute_process(COMMAND "${LUNA_COMPILED_PROBE_EXECUTABLE}" --compiled-fragment-cost
            "${LUNA_COMPILED_PROBE_ITERATIONS}" 9 "${profile}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 180)
    if(NOT status EQUAL 0 OR NOT errors STREQUAL "")
        message(FATAL_ERROR "compiled series process ${process}/${profile} failed (${status}): ${errors}")
    endif()
    string(REPLACE "\r\n" "\n" output "${output}")
    luna_validate_compiled_probe("${output}" "${LUNA_COMPILED_PROBE_ITERATIONS}" "${profile}")
    luna_compiled_series_identity("${output}" "${profile}")
    set(record_${process} "${output}")
    set(filename "process-${process}-${profile}.csv")
    set(filename_${process} "${filename}")
    set(manifest_row_${process} "${process},${cycle},${block},${position},${profile},${filename}")
    string(REPLACE "\n" ";" lines "${output}")
    foreach(line IN LISTS lines)
        if(line MATCHES "^[0-9]+,")
            string(APPEND combined "${process},${cycle},${block},${position},${profile},${line}\n")
        endif()
    endforeach()
endforeach()
math(EXPR samples "${process} * 81")
math(EXPR visits "${LUNA_COMPILED_SERIES_CYCLES} * 2")
set(manifest "# protocol=luna.compiled-fragment-series.v1\n# probe_protocol=${series_protocol}\n")
string(APPEND manifest "# series_runner_sha256=${runner_hash}\n# protocol_validator_sha256=${validator_hash}\n")
foreach(key IN ITEMS git_commit probe_sha256 workload_sha256 build_type compiler cxx target data_layout
        host_container_sha256 plugin_container_sha256 orc_codegen affinity timed_harness iterations)
    string(APPEND manifest "# ${key}=${series_${key}}\n")
endforeach()
foreach(profile IN ITEMS O0 O2 O3)
    string(APPEND manifest "# materialization_key_${profile}=${series_key_${profile}}\n")
endforeach()
string(APPEND manifest "# cycles=${LUNA_COMPILED_SERIES_CYCLES},blocks_per_cycle=6\n")
string(APPEND manifest "# measured_processes=${process},fresh_process_per_record=yes\n")
string(APPEND manifest "# verified_samples=${samples},profile_position_visits=${visits}\n")
string(APPEND manifest "# within_block_directed_pair_visits=${visits},between_block_balance=unclaimed\n")
# No output before all processes and common identities validate. The manifest
# is the last file: an interrupted write cannot masquerade as a complete bundle.
file(SHA256 "${CMAKE_CURRENT_LIST_FILE}" final_runner_hash)
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_protocol.cmake" final_validator_hash)
if(NOT runner_hash STREQUAL final_runner_hash OR NOT validator_hash STREQUAL final_validator_hash)
    message(FATAL_ERROR "compiled series orchestration sources changed during sampling")
endif()
if(EXISTS "${output_dir}")
    message(FATAL_ERROR "compiled series output directory appeared during sampling")
endif()
file(MAKE_DIRECTORY "${output_dir}")
set(manifest_rows "process,cycle,block,profile_position,profile,record,sha256\n")
foreach(index RANGE 1 ${process})
    file(WRITE "${output_dir}/${filename_${index}}" "${record_${index}}")
    file(READ "${output_dir}/${filename_${index}}" written)
    string(REPLACE "\r\n" "\n" written "${written}")
    if(NOT written STREQUAL record_${index})
        message(FATAL_ERROR "compiled series record write changed content")
    endif()
    file(SHA256 "${output_dir}/${filename_${index}}" written_hash)
    string(APPEND manifest_rows "${manifest_row_${index}},${written_hash}\n")
endforeach()
file(WRITE "${output_dir}/samples.csv" "${combined}")
file(READ "${output_dir}/samples.csv" written)
string(REPLACE "\r\n" "\n" written "${written}")
if(NOT written STREQUAL combined)
    message(FATAL_ERROR "compiled series combined write changed content")
endif()
file(SHA256 "${output_dir}/samples.csv" combined_hash)
string(APPEND manifest "# combined_sha256=${combined_hash}\n${manifest_rows}")
file(WRITE "${output_dir}/manifest.csv" "${manifest}")
message(STATUS "Compiled Fragment series: ${process} fresh processes, ${samples} samples, balanced within blocks; no timing threshold")
