cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_bundle.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_fixture.cmake")

if(NOT DEFINED LUNA_COMPILED_BUNDLE_TEST_ROOT)
    message(FATAL_ERROR "synthetic bundle test requires a build-tree root")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
get_filename_component(test_root "${LUNA_COMPILED_BUNDLE_TEST_ROOT}/session-${nonce}" ABSOLUTE)
if(EXISTS "${test_root}")
    message(FATAL_ERROR "synthetic bundle test directory already exists")
endif()

# Generated test fixtures live only in the build tree. No timing binary runs,
# and no observation directory is overwritten or recursively removed.
function(bundle_fixture directory cycles)
    file(MAKE_DIRECTORY "${directory}")
    luna_compiled_series_schedule("${cycles}" schedule)
    set(combined "process,cycle,block,profile_position,profile,round,position,case,ns_per_op,calls,checksum\n")
    set(rows "process,cycle,block,profile_position,profile,record,sha256\n")
    set(index 0)
    foreach(item IN LISTS schedule)
        math(EXPR index "${index} + 1")
        string(REPLACE "," ";" fields "${item}")
        list(GET fields 3 profile)
        luna_compiled_probe_fixture("${profile}" record)
        string(REPEAT a 40 commit)
        string(REPLACE "git_commit=synthetic-test-only" "git_commit=${commit}" record "${record}")
        luna_compiled_series_identity("${record}" "${profile}")
        set(filename "process-${index}-${profile}.csv")
        set(written "${record}")
        if(ARGC GREATER 2 AND ARGV2 STREQUAL "CRLF")
            string(REPLACE "\n" "\r\n" written "${written}")
        endif()
        file(WRITE "${directory}/${filename}" "${written}")
        file(SHA256 "${directory}/${filename}" hash)
        string(APPEND rows "${index},${item},${filename},${hash}\n")
        string(REPLACE "\n" ";" lines "${record}")
        foreach(line IN LISTS lines)
            if(line MATCHES "^[0-9]+,")
                string(APPEND combined "${index},${item},${line}\n")
            endif()
        endforeach()
    endforeach()
    set(manifest "# protocol=luna.compiled-fragment-series.v1\n# probe_protocol=${series_protocol}\n")
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/compiled_fragment_series.cmake" hash)
    string(APPEND manifest "# series_runner_sha256=${hash}\n")
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/compiled_fragment_probe_protocol.cmake" hash)
    string(APPEND manifest "# protocol_validator_sha256=${hash}\n")
    foreach(key IN ITEMS git_commit probe_sha256 workload_sha256 build_type compiler cxx target data_layout
            host_container_sha256 plugin_container_sha256 orc_codegen affinity timed_harness iterations)
        string(APPEND manifest "# ${key}=${series_${key}}\n")
    endforeach()
    foreach(profile IN ITEMS O0 O2 O3)
        string(APPEND manifest "# materialization_key_${profile}=${series_key_${profile}}\n")
    endforeach()
    math(EXPR samples "${index} * 81")
    math(EXPR visits "${cycles} * 2")
    string(APPEND manifest "# cycles=${cycles},blocks_per_cycle=6\n")
    string(APPEND manifest "# measured_processes=${index},fresh_process_per_record=yes\n")
    string(APPEND manifest "# verified_samples=${samples},profile_position_visits=${visits}\n")
    string(APPEND manifest "# within_block_directed_pair_visits=${visits},between_block_balance=unclaimed\n")
    if(ARGC GREATER 2 AND ARGV2 STREQUAL "CRLF")
        string(REPLACE "\n" "\r\n" combined "${combined}")
    endif()
    file(WRITE "${directory}/samples.csv" "${combined}")
    file(SHA256 "${directory}/samples.csv" hash)
    string(APPEND manifest "# combined_sha256=${hash}\n${rows}")
    if(ARGC GREATER 2 AND ARGV2 STREQUAL "CRLF")
        string(REPLACE "\n" "\r\n" manifest "${manifest}")
    endif()
    file(WRITE "${directory}/manifest.csv" "${manifest}")
endfunction()

function(rehash_manifest_file directory filename metadata_key)
    file(READ "${directory}/manifest.csv" manifest)
    file(SHA256 "${directory}/${filename}" hash)
    if(metadata_key STREQUAL "")
        string(REGEX REPLACE "(${filename},)[0-9a-f]+" "\\1${hash}" manifest "${manifest}")
    else()
        string(REGEX REPLACE "(# ${metadata_key}=)[0-9a-f]+" "\\1${hash}" manifest "${manifest}")
    endif()
    file(WRITE "${directory}/manifest.csv" "${manifest}")
endfunction()

if(DEFINED BUNDLE_TEST_CASE)
    set(directory "${test_root}/damaged")
    bundle_fixture("${directory}" 1)
    file(READ "${directory}/manifest.csv" manifest)
    if(BUNDLE_TEST_CASE STREQUAL missing_manifest)
        # A partial bundle directory, not a destructive removal of a fixture.
        file(MAKE_DIRECTORY "${test_root}/partial")
        set(directory "${test_root}/partial")
    elseif(BUNDLE_TEST_CASE STREQUAL missing_record)
        file(RENAME "${directory}/process-1-O0.csv" "${test_root}/retained-record.csv")
    elseif(BUNDLE_TEST_CASE STREQUAL symlink_record)
        file(RENAME "${directory}/process-1-O0.csv" "${test_root}/retained-record.csv")
        file(CREATE_LINK "${test_root}/retained-record.csv" "${directory}/process-1-O0.csv" SYMBOLIC)
    elseif(BUNDLE_TEST_CASE STREQUAL duplicate_metadata)
        string(APPEND manifest "# target=synthetic\n")
    elseif(BUNDLE_TEST_CASE STREQUAL unknown_metadata)
        string(APPEND manifest "# unexpected=value\n")
    elseif(BUNDLE_TEST_CASE STREQUAL digest_suffix)
        string(REGEX REPLACE "(# combined_sha256=[0-9a-f]+)" "\\1suffix" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_protocol)
        string(REPLACE "series.v1" "series.v9" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_count)
        string(REPLACE "measured_processes=18" "measured_processes=17" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_source)
        string(REPEAT c 64 hash)
        string(REGEX REPLACE "(# series_runner_sha256=)[0-9a-f]+" "\\1${hash}" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_identity)
        string(REPLACE "compiler=synthetic" "compiler=different" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_key)
        string(REPLACE "ir=O0:orc=default" "ir=O3:orc=default" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL duplicate_header)
        string(APPEND manifest "process,cycle,block,profile_position,profile,record,sha256\n")
    elseif(BUNDLE_TEST_CASE STREQUAL truncated_manifest)
        string(REGEX REPLACE "18,1,6,3,O0,[^\n]+\n" "" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL reversed_order)
        string(REPLACE "1,1,1,1,O0," "2,1,1,1,O0," manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL path_escape)
        string(REPLACE "process-1-O0.csv" "../process-1-O0.csv" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL absolute_path)
        string(REPLACE "process-1-O0.csv" "/process-1-O0.csv" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL semicolon)
        string(APPEND manifest ";\n")
    elseif(BUNDLE_TEST_CASE STREQUAL extra_file)
        file(WRITE "${directory}/unlisted.txt" "synthetic\n")
    elseif(BUNDLE_TEST_CASE STREQUAL extra_directory)
        file(MAKE_DIRECTORY "${directory}/unlisted")
    elseif(BUNDLE_TEST_CASE STREQUAL raw_hash)
        file(APPEND "${directory}/process-1-O0.csv" "# harmless-comment\n")
    elseif(BUNDLE_TEST_CASE STREQUAL combined_hash)
        file(APPEND "${directory}/samples.csv" "extra\n")
    elseif(BUNDLE_TEST_CASE STREQUAL checksum_rehashed OR BUNDLE_TEST_CASE STREQUAL raw_identity_rehashed)
        file(READ "${directory}/process-1-O0.csv" record)
        if(BUNDLE_TEST_CASE STREQUAL checksum_rehashed)
            string(REPLACE "1,1,plain,0.0,6,120" "1,1,plain,0.0,6,121" record "${record}")
        else()
            string(REPLACE "compiler=synthetic" "compiler=different" record "${record}")
        endif()
        file(WRITE "${directory}/process-1-O0.csv" "${record}")
        rehash_manifest_file("${directory}" process-1-O0.csv "")
        file(READ "${directory}/manifest.csv" manifest)
    elseif(BUNDLE_TEST_CASE STREQUAL combined_rehashed)
        file(READ "${directory}/samples.csv" combined)
        string(REPLACE "0.0,6,120" "1.0,6,120" combined "${combined}")
        file(WRITE "${directory}/samples.csv" "${combined}")
        rehash_manifest_file("${directory}" samples.csv combined_sha256)
        file(READ "${directory}/manifest.csv" manifest)
    elseif(BUNDLE_TEST_CASE STREQUAL oversized_manifest)
        string(REPEAT x 65537 manifest)
    elseif(BUNDLE_TEST_CASE STREQUAL oversized_record)
        string(REPEAT x 65537 record)
        file(WRITE "${directory}/process-1-O0.csv" "${record}")
    elseif(BUNDLE_TEST_CASE STREQUAL expected_commit)
        string(REPEAT b 40 LUNA_COMPILED_BUNDLE_EXPECTED_COMMIT)
    elseif(BUNDLE_TEST_CASE STREQUAL invalid_commit)
        set(LUNA_COMPILED_BUNDLE_EXPECTED_COMMIT short)
    elseif(BUNDLE_TEST_CASE STREQUAL expected_manifest)
        string(REPEAT b 64 LUNA_COMPILED_BUNDLE_EXPECTED_MANIFEST_SHA256)
    elseif(BUNDLE_TEST_CASE STREQUAL invalid_manifest_anchor)
        set(LUNA_COMPILED_BUNDLE_EXPECTED_MANIFEST_SHA256 short)
    elseif(BUNDLE_TEST_CASE STREQUAL empty_record)
        file(WRITE "${directory}/process-1-O0.csv" "")
    else()
        message(FATAL_ERROR "unknown synthetic bundle test")
    endif()
    if(NOT BUNDLE_TEST_CASE STREQUAL missing_manifest)
        file(WRITE "${directory}/manifest.csv" "${manifest}")
    endif()
    luna_validate_compiled_bundle("${directory}")
    message(FATAL_ERROR "damaged synthetic bundle was accepted")
endif()

foreach(configuration IN ITEMS "1/LF" "1/CRLF" "2/LF" "10/LF")
    string(REPLACE "/" ";" fields "${configuration}")
    list(GET fields 0 cycles)
    list(GET fields 1 eol)
    set(directory "${test_root}/valid-${cycles}-${eol}")
    bundle_fixture("${directory}" "${cycles}" "${eol}")
    string(REPEAT a 40 LUNA_COMPILED_BUNDLE_EXPECTED_COMMIT)
    file(SHA256 "${directory}/manifest.csv" LUNA_COMPILED_BUNDLE_EXPECTED_MANIFEST_SHA256)
    file(GLOB paths "${directory}/*")
    set(before "")
    foreach(path IN LISTS paths)
        file(SHA256 "${path}" hash)
        string(APPEND before "${path}:${hash}\n")
    endforeach()
    luna_validate_compiled_bundle("${directory}")
    set(after "")
    foreach(path IN LISTS paths)
        file(SHA256 "${path}" hash)
        string(APPEND after "${path}:${hash}\n")
    endforeach()
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "read-only bundle acceptance modified files")
    endif()
endforeach()
set(rejections "missing_manifest|regular non-symlink" "missing_record|regular non-symlink"
        "duplicate_metadata|exactly once" "unknown_metadata|unknown manifest"
        "digest_suffix|invalid SHA-256" "wrong_protocol|unsupported protocol"
        "wrong_count|count/balance" "wrong_source|orchestration source"
        "wrong_identity|manifest/raw identity" "wrong_key|materialization key"
        "duplicate_header|header misplaced" "truncated_manifest|process count/header"
        "reversed_order|process/order" "path_escape|record path" "absolute_path|record path"
        "semicolon|semicolon" "extra_file|unlisted" "extra_directory|unlisted"
        "raw_hash|raw-file SHA-256" "combined_hash|combined SHA-256"
        "checksum_rehashed|checksum mismatch" "raw_identity_rehashed|manifest/raw identity"
        "combined_rehashed|combined rows" "oversized_manifest|size limit" "oversized_record|size limit"
        "expected_commit|expected commit mismatch" "invalid_commit|full lowercase"
        "expected_manifest|expected manifest SHA-256 mismatch"
        "invalid_manifest_anchor|invalid SHA-256" "empty_record|size limit")
if(UNIX)
    list(APPEND rejections "symlink_record|regular non-symlink")
endif()
foreach(test IN LISTS rejections)
    string(REPLACE "|" ";" fields "${test}")
    list(GET fields 0 name)
    list(GET fields 1 expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -Werror=dev "-DBUNDLE_TEST_CASE=${name}"
            "-DLUNA_COMPILED_BUNDLE_TEST_ROOT=${test_root}/children" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT status EQUAL 1 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "synthetic bundle rejection ${name} failed (${status}): ${output}${errors}")
    endif()
endforeach()
message(STATUS "Compiled Fragment offline bundle acceptance: synthetic fixtures only, read-only checks; no timing probe")
