cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_pinned_bundle.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_pinned_fixture.cmake")

if(NOT DEFINED LUNA_COMPILED_PINNED_BUNDLE_TEST_ROOT)
    message(FATAL_ERROR "synthetic bundle test requires a build-tree root")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
get_filename_component(test_root "${LUNA_COMPILED_PINNED_BUNDLE_TEST_ROOT}/session-${nonce}" ABSOLUTE)
if(EXISTS "${test_root}")
    message(FATAL_ERROR "synthetic bundle test directory already exists")
endif()

# Generated test fixtures live only in the build tree. No timing binary runs,
# and no observation directory is overwritten or recursively removed.

function(rehash_manifest_file directory filename metadata_key)
    file(READ "${directory}/manifest.csv" manifest)
    file(SHA256 "${directory}/${filename}" hash)
    if(metadata_key STREQUAL "")
        string(REGEX REPLACE "(${filename},)[0-9a-f]+" "\\1${hash}" manifest "${manifest}")
    else()
        string(REGEX REPLACE "(# ${metadata_key}=)[0-9a-f]+" "\\1${hash}" manifest "${manifest}")
    endif()
    file(WRITE "${directory}/manifest.csv" "${manifest}")
endfunction()

if(DEFINED BUNDLE_TEST_CASE)
    set(directory "${test_root}/damaged")
    luna_compiled_pinned_bundle_fixture("${directory}" 1)
    file(READ "${directory}/manifest.csv" manifest)
    if(BUNDLE_TEST_CASE STREQUAL default_reader_rejects_pinned)
        luna_validate_compiled_bundle("${directory}")
    elseif(BUNDLE_TEST_CASE STREQUAL pinned_reader_rejects_default)
        set(directory "${test_root}/legacy")
        luna_compiled_bundle_fixture("${directory}" 1)
        file(READ "${directory}/manifest.csv" manifest)
    elseif(BUNDLE_TEST_CASE STREQUAL missing_control)
        string(REGEX REPLACE "# affinity_control_sha256=[^\n]+\n" "" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_control OR BUNDLE_TEST_CASE STREQUAL wrong_pinned_validator)
        string(REPEAT c 64 changed)
        set(key affinity_control_sha256)
        if(BUNDLE_TEST_CASE STREQUAL wrong_pinned_validator)
            set(key pinned_protocol_validator_sha256)
        endif()
        string(REGEX REPLACE "(# ${key}=)[0-9a-f]+" "\\1${changed}" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL invalid_cpu)
        string(REPLACE "# logical_cpu=19" "# logical_cpu=019" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL changed_cpu)
        string(REPLACE "# logical_cpu=19" "# logical_cpu=18" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL changed_group)
        string(REPLACE "# processor_group=0" "# processor_group=none" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL changed_scope)
        string(REPLACE "setup_affinity=uncontrolled" "setup_affinity=controlled" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL raw_control_rehashed OR BUNDLE_TEST_CASE STREQUAL mixed_record_rehashed)
        file(READ "${directory}/process-1-O0.csv" record)
        if(BUNDLE_TEST_CASE STREQUAL raw_control_rehashed)
            string(REPEAT c 64 changed)
            string(REGEX REPLACE "(# affinity_control_sha256=)[0-9a-f]+" "\\1${changed}" record "${record}")
        else()
            luna_compiled_probe_fixture(O0 record)
        endif()
        file(WRITE "${directory}/process-1-O0.csv" "${record}")
        rehash_manifest_file("${directory}" process-1-O0.csv "")
        file(READ "${directory}/manifest.csv" manifest)
    elseif(BUNDLE_TEST_CASE STREQUAL occupied_output)
        set(LUNA_COMPILED_PROBE_EXECUTABLE "${CMAKE_COMMAND}")
        set(LUNA_COMPILED_PROBE_LOGICAL_CPU 0)
        set(LUNA_COMPILED_PINNED_SERIES_OUTPUT_DIR "${directory}")
        include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_pinned_series.cmake")
    elseif(BUNDLE_TEST_CASE STREQUAL invalid_requested_cpu)
        set(LUNA_COMPILED_PROBE_EXECUTABLE "${CMAKE_COMMAND}")
        set(LUNA_COMPILED_PROBE_LOGICAL_CPU 01)
        set(LUNA_COMPILED_PINNED_SERIES_OUTPUT_DIR "${test_root}/not-created")
        include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_pinned_series.cmake")
    elseif(BUNDLE_TEST_CASE STREQUAL missing_manifest)
        # A partial bundle directory, not a destructive removal of a fixture.
        file(MAKE_DIRECTORY "${test_root}/partial")
        set(directory "${test_root}/partial")
    elseif(BUNDLE_TEST_CASE STREQUAL missing_record)
        file(RENAME "${directory}/process-1-O0.csv" "${test_root}/retained-record.csv")
    elseif(BUNDLE_TEST_CASE STREQUAL symlink_record)
        file(RENAME "${directory}/process-1-O0.csv" "${test_root}/retained-record.csv")
        file(CREATE_LINK "${test_root}/retained-record.csv" "${directory}/process-1-O0.csv" SYMBOLIC)
    elseif(BUNDLE_TEST_CASE STREQUAL duplicate_metadata)
        string(APPEND manifest "# target=synthetic\n")
    elseif(BUNDLE_TEST_CASE STREQUAL unknown_metadata)
        string(APPEND manifest "# unexpected=value\n")
    elseif(BUNDLE_TEST_CASE STREQUAL digest_suffix)
        string(REGEX REPLACE "(# combined_sha256=[0-9a-f]+)" "\\1suffix" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_protocol)
        string(REPLACE "series.v1" "series.v9" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_count)
        string(REPLACE "measured_processes=18" "measured_processes=17" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_source)
        string(REPEAT c 64 hash)
        string(REGEX REPLACE "(# series_runner_sha256=)[0-9a-f]+" "\\1${hash}" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_identity)
        string(REPLACE "compiler=synthetic" "compiler=different" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL wrong_key)
        string(REPLACE "ir=O0:orc=default" "ir=O3:orc=default" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL duplicate_header)
        string(APPEND manifest "process,cycle,block,profile_position,profile,record,sha256\n")
    elseif(BUNDLE_TEST_CASE STREQUAL truncated_manifest)
        string(REGEX REPLACE "18,1,6,3,O0,[^\n]+\n" "" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL reversed_order)
        string(REPLACE "1,1,1,1,O0," "2,1,1,1,O0," manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL path_escape)
        string(REPLACE "process-1-O0.csv" "../process-1-O0.csv" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL absolute_path)
        string(REPLACE "process-1-O0.csv" "/process-1-O0.csv" manifest "${manifest}")
    elseif(BUNDLE_TEST_CASE STREQUAL semicolon)
        string(APPEND manifest ";\n")
    elseif(BUNDLE_TEST_CASE STREQUAL extra_file)
        file(WRITE "${directory}/unlisted.txt" "synthetic\n")
    elseif(BUNDLE_TEST_CASE STREQUAL extra_directory)
        file(MAKE_DIRECTORY "${directory}/unlisted")
    elseif(BUNDLE_TEST_CASE STREQUAL raw_hash)
        file(APPEND "${directory}/process-1-O0.csv" "# harmless-comment\n")
    elseif(BUNDLE_TEST_CASE STREQUAL combined_hash)
        file(APPEND "${directory}/samples.csv" "extra\n")
    elseif(BUNDLE_TEST_CASE STREQUAL checksum_rehashed OR BUNDLE_TEST_CASE STREQUAL raw_identity_rehashed)
        file(READ "${directory}/process-1-O0.csv" record)
        if(BUNDLE_TEST_CASE STREQUAL checksum_rehashed)
            string(REPLACE "1,1,plain,0.0,6,120" "1,1,plain,0.0,6,121" record "${record}")
        else()
            string(REPLACE "compiler=synthetic" "compiler=different" record "${record}")
        endif()
        file(WRITE "${directory}/process-1-O0.csv" "${record}")
        rehash_manifest_file("${directory}" process-1-O0.csv "")
        file(READ "${directory}/manifest.csv" manifest)
    elseif(BUNDLE_TEST_CASE STREQUAL combined_rehashed)
        file(READ "${directory}/samples.csv" combined)
        string(REPLACE "0.0,6,120" "1.0,6,120" combined "${combined}")
        file(WRITE "${directory}/samples.csv" "${combined}")
        rehash_manifest_file("${directory}" samples.csv combined_sha256)
        file(READ "${directory}/manifest.csv" manifest)
    elseif(BUNDLE_TEST_CASE STREQUAL oversized_manifest)
        string(REPEAT x 65537 manifest)
    elseif(BUNDLE_TEST_CASE STREQUAL oversized_record)
        string(REPEAT x 65537 record)
        file(WRITE "${directory}/process-1-O0.csv" "${record}")
    elseif(BUNDLE_TEST_CASE STREQUAL expected_commit)
        string(REPEAT b 40 LUNA_COMPILED_PINNED_BUNDLE_EXPECTED_COMMIT)
    elseif(BUNDLE_TEST_CASE STREQUAL invalid_commit)
        set(LUNA_COMPILED_PINNED_BUNDLE_EXPECTED_COMMIT short)
    elseif(BUNDLE_TEST_CASE STREQUAL expected_manifest)
        string(REPEAT b 64 LUNA_COMPILED_PINNED_BUNDLE_EXPECTED_MANIFEST_SHA256)
    elseif(BUNDLE_TEST_CASE STREQUAL invalid_manifest_anchor)
        set(LUNA_COMPILED_PINNED_BUNDLE_EXPECTED_MANIFEST_SHA256 short)
    elseif(BUNDLE_TEST_CASE STREQUAL empty_record)
        file(WRITE "${directory}/process-1-O0.csv" "")
    else()
        message(FATAL_ERROR "unknown synthetic bundle test")
    endif()
    if(NOT BUNDLE_TEST_CASE STREQUAL missing_manifest)
        file(WRITE "${directory}/manifest.csv" "${manifest}")
    endif()
    luna_validate_compiled_pinned_bundle("${directory}")
    message(FATAL_ERROR "damaged synthetic bundle was accepted")
endif()

foreach(configuration IN ITEMS "1/LF" "1/CRLF" "2/LF" "10/LF")
    string(REPLACE "/" ";" fields "${configuration}")
    list(GET fields 0 cycles)
    list(GET fields 1 eol)
    set(directory "${test_root}/valid-${cycles}-${eol}")
    luna_compiled_pinned_bundle_fixture("${directory}" "${cycles}" "${eol}")
    string(REPEAT a 40 LUNA_COMPILED_PINNED_BUNDLE_EXPECTED_COMMIT)
    file(SHA256 "${directory}/manifest.csv" LUNA_COMPILED_PINNED_BUNDLE_EXPECTED_MANIFEST_SHA256)
    file(GLOB paths "${directory}/*")
    set(before "")
    foreach(path IN LISTS paths)
        file(SHA256 "${path}" hash)
        string(APPEND before "${path}:${hash}\n")
    endforeach()
    luna_validate_compiled_pinned_bundle("${directory}")
    set(after "")
    foreach(path IN LISTS paths)
        file(SHA256 "${path}" hash)
        string(APPEND after "${path}:${hash}\n")
    endforeach()
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "read-only bundle acceptance modified files")
    endif()
endforeach()
set(rejections "missing_manifest|regular non-symlink" "missing_record|regular non-symlink"
        "duplicate_metadata|exactly once" "unknown_metadata|unknown manifest"
        "digest_suffix|invalid SHA-256" "wrong_protocol|unsupported protocol"
        "wrong_count|count/balance" "wrong_source|orchestration source"
        "wrong_identity|manifest/raw identity" "wrong_key|materialization key"
        "duplicate_header|header misplaced" "truncated_manifest|process count/header"
        "reversed_order|process/order" "path_escape|record path" "absolute_path|record path"
        "semicolon|semicolon" "extra_file|unlisted" "extra_directory|unlisted"
        "raw_hash|raw-file SHA-256" "combined_hash|combined SHA-256"
        "checksum_rehashed|checksum mismatch" "raw_identity_rehashed|manifest/raw identity"
        "combined_rehashed|combined rows" "oversized_manifest|size limit" "oversized_record|size limit"
        "expected_commit|expected commit mismatch" "invalid_commit|full lowercase"
        "expected_manifest|expected manifest SHA-256 mismatch"
        "invalid_manifest_anchor|invalid SHA-256" "empty_record|size limit")
list(APPEND rejections "default_reader_rejects_pinned|unsupported protocol"
    "pinned_reader_rejects_default|unsupported protocol" "missing_control|exactly once"
    "wrong_control|controller/validator source" "wrong_pinned_validator|controller/validator source"
    "invalid_cpu|invalid CPU/group" "changed_cpu|pinned probe metadata mismatch"
    "changed_group|pinned probe metadata mismatch" "changed_scope|manifest/raw identity"
    "raw_control_rehashed|pinned probe metadata mismatch" "mixed_record_rehashed|pinned probe metadata mismatch"
    "occupied_output|already exists" "invalid_requested_cpu|explicit canonical")
if(UNIX)
    list(APPEND rejections "symlink_record|regular non-symlink")
endif()
set(warning_option -Werror=dev)
if(CMAKE_VERSION VERSION_GREATER_EQUAL 4.4)
    set(warning_option -Werror=author)
endif()
foreach(test IN LISTS rejections)
    string(REPLACE "|" ";" fields "${test}")
    list(GET fields 0 name)
    list(GET fields 1 expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "${warning_option}" "-DBUNDLE_TEST_CASE=${name}"
            "-DLUNA_COMPILED_PINNED_BUNDLE_TEST_ROOT=${test_root}/children" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT status EQUAL 1 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "synthetic bundle rejection ${name} failed (${status}): ${output}${errors}")
    endif()
endforeach()
# A failed launch/unsupported platform must not publish even a partial output
# directory. The child is CMake, not a timing probe or a filesystem-writing mock.
set(failed_output "${test_root}/failed-sampling")
execute_process(COMMAND "${CMAKE_COMMAND}" "${warning_option}"
        "-DLUNA_COMPILED_PROBE_EXECUTABLE=${CMAKE_COMMAND}" -DLUNA_COMPILED_PROBE_LOGICAL_CPU=0
        "-DLUNA_COMPILED_PINNED_SERIES_OUTPUT_DIR=${failed_output}"
        -P "${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_pinned_series.cmake"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 1 OR NOT output STREQUAL "" OR errors STREQUAL "" OR
   EXISTS "${failed_output}" OR IS_SYMLINK "${failed_output}")
    message(FATAL_ERROR "failed sampling produced output or passed: ${status}: ${output}${errors}")
endif()
message(STATUS "Compiled Fragment pinned offline bundle acceptance: synthetic fixtures only, read-only checks; no timing probe")
