cmake_minimum_required(VERSION 3.20)

# Synthetic records only: zero latency is deliberately valid. Never runs JIT.
function(luna_compiled_probe_fixture profile result)
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmarks/compiled_fragment_benchmark.cpp" probe_hash)
    set(workload_input "")
    foreach(path IN ITEMS host/luna.package host/src/effects.luna luna.lock luna.workspace
                          plugin/luna.package plugin/src/effects.luna)
        file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmarks/compiled_fragment/${path}" hash)
        string(APPEND workload_input "${path}:${hash}\n")
    endforeach()
    string(SHA256 workload_hash "${workload_input}")
    string(REPEAT a 64 host_hash)
    string(REPEAT b 64 plugin_hash)
    set(output "# protocol=luna.compiled-fragment-cost.v2\n# git_commit=synthetic-test-only\n")
    string(APPEND output "# probe_sha256=${probe_hash}\n# workload_sha256=${workload_hash}\n")
    string(APPEND output "# build_type=synthetic\n# compiler=synthetic\n# cxx=201703,llvm=synthetic\n")
    string(APPEND output "# target=synthetic\n# data_layout=synthetic\n")
    string(APPEND output "# host_container_sha256=${host_hash}\n# plugin_container_sha256=${plugin_hash}\n")
    string(APPEND output "# moonir_optimization=O2,llvm_optimization=${profile}\n# orc_codegen=default\n")
    string(APPEND output "# materialization_key=luna.verified-moon-jit.v1:llvm=synthetic:ir=${profile}:orc=default\n")
    string(APPEND output "# candidate_count=4,host_order=resume_a/resume_b/resume_c/resume_d\n")
    string(APPEND output "# correctness_checks=320,runtime_alive_during_samples=no\n")
    foreach(key IN ITEMS compile_encode_decode_ms verified_load_jit_ms discovery_binding_ms)
        string(APPEND output "# ${key}=0.000\n")
    endforeach()
    string(APPEND output "# iterations=3,warmup=3,rounds=9\n# affinity=uncontrolled,power_policy=uncontrolled\n")
    string(APPEND output "# timed_harness=case_branch+input_modulo+JIT_call+checksum\n")
    string(APPEND output "round,position,case,ns_per_op,calls,checksum\n")
    set(cases plain private_erased static_resume static_discard dynamic_none dynamic_one
        dynamic_chain_2 dynamic_chain_4 dynamic_override_none)
    foreach(sample RANGE 0 80)
        math(EXPR round "${sample} / 9 + 1")
        math(EXPR position "${sample} % 9 + 1")
        math(EXPR index "(${position} - 1 + (${round} - 1) * 4) % 9")
        list(GET cases ${index} name)
        set(checksum 120)
        if(index EQUAL 3)
            set(checksum 18)
        endif()
        string(APPEND output "${round},${position},${name},0.0,6,${checksum}\n")
    endforeach()
    string(APPEND output "# verified_samples=81,position_balanced=yes\n")
    set(${result} "${output}" PARENT_SCOPE)
endfunction()

function(luna_compiled_bundle_fixture directory cycles)
    file(MAKE_DIRECTORY "${directory}")
    luna_compiled_series_schedule("${cycles}" schedule)
    set(combined "process,cycle,block,profile_position,profile,round,position,case,ns_per_op,calls,checksum\n")
    set(rows "process,cycle,block,profile_position,profile,record,sha256\n")
    set(index 0)
    foreach(item IN LISTS schedule)
        math(EXPR index "${index} + 1")
        string(REPLACE "," ";" fields "${item}")
        list(GET fields 3 profile)
        luna_compiled_probe_fixture("${profile}" record)
        string(REPEAT a 40 commit)
        string(REPLACE "git_commit=synthetic-test-only" "git_commit=${commit}" record "${record}")
        luna_compiled_series_identity("${record}" "${profile}")
        set(filename "process-${index}-${profile}.csv")
        set(written "${record}")
        if(ARGC GREATER 2 AND ARGV2 STREQUAL "CRLF")
            string(REPLACE "\n" "\r\n" written "${written}")
        endif()
        file(WRITE "${directory}/${filename}" "${written}")
        file(SHA256 "${directory}/${filename}" hash)
        string(APPEND rows "${index},${item},${filename},${hash}\n")
        string(REPLACE "\n" ";" lines "${record}")
        foreach(line IN LISTS lines)
            if(line MATCHES "^[0-9]+,")
                string(APPEND combined "${index},${item},${line}\n")
            endif()
        endforeach()
    endforeach()
    set(manifest "# protocol=luna.compiled-fragment-series.v1\n# probe_protocol=${series_protocol}\n")
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/compiled_fragment_series.cmake" hash)
    string(APPEND manifest "# series_runner_sha256=${hash}\n")
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/compiled_fragment_probe_protocol.cmake" hash)
    string(APPEND manifest "# protocol_validator_sha256=${hash}\n")
    foreach(key IN ITEMS git_commit probe_sha256 workload_sha256 build_type compiler cxx target data_layout
            host_container_sha256 plugin_container_sha256 orc_codegen affinity timed_harness iterations)
        string(APPEND manifest "# ${key}=${series_${key}}\n")
    endforeach()
    foreach(profile IN ITEMS O0 O2 O3)
        string(APPEND manifest "# materialization_key_${profile}=${series_key_${profile}}\n")
    endforeach()
    math(EXPR samples "${index} * 81")
    math(EXPR visits "${cycles} * 2")
    string(APPEND manifest "# cycles=${cycles},blocks_per_cycle=6\n")
    string(APPEND manifest "# measured_processes=${index},fresh_process_per_record=yes\n")
    string(APPEND manifest "# verified_samples=${samples},profile_position_visits=${visits}\n")
    string(APPEND manifest "# within_block_directed_pair_visits=${visits},between_block_balance=unclaimed\n")
    if(ARGC GREATER 2 AND ARGV2 STREQUAL "CRLF")
        string(REPLACE "\n" "\r\n" combined "${combined}")
    endif()
    file(WRITE "${directory}/samples.csv" "${combined}")
    file(SHA256 "${directory}/samples.csv" hash)
    string(APPEND manifest "# combined_sha256=${hash}\n${rows}")
    if(ARGC GREATER 2 AND ARGV2 STREQUAL "CRLF")
        string(REPLACE "\n" "\r\n" manifest "${manifest}")
    endif()
    file(WRITE "${directory}/manifest.csv" "${manifest}")
endfunction()
