cmake_minimum_required(VERSION 3.20)
# CMake 4.4 renamed the dev diagnostic category to author. Preserve the
# warning-error option without CLI deprecation output on newer CMake.
if(CMAKE_VERSION VERSION_GREATER_EQUAL 4.4)
    set(author_warning_error -Werror=author)
else()
    set(author_warning_error -Werror=dev)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/../tools/package_compiled_fragment_pinned_evidence.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_fixture.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_pinned_fixture.cmake")
if(NOT DEFINED LUNA_COMPILED_EVIDENCE_TEST_ROOT)
    message(FATAL_ERROR "synthetic evidence test requires a build-tree root")
endif()
if(NOT DEFINED LUNA_COMPILED_EVIDENCE_TEST_MODE)
    set(LUNA_COMPILED_EVIDENCE_TEST_MODE uncontrolled)
endif()
if(LUNA_COMPILED_EVIDENCE_TEST_MODE STREQUAL uncontrolled)
    set(anchor LUNA_COMPILED_EVIDENCE)
    set(bundle_anchor LUNA_COMPILED_BUNDLE)
    set(reader compiled_fragment_bundle.cmake)
    set(expected_sources 12)
elseif(LUNA_COMPILED_EVIDENCE_TEST_MODE STREQUAL pinned)
    set(anchor LUNA_COMPILED_PINNED_EVIDENCE)
    set(bundle_anchor LUNA_COMPILED_PINNED_BUNDLE)
    set(reader compiled_fragment_pinned_bundle.cmake)
    set(expected_sources 17)
else()
    message(FATAL_ERROR "unsupported synthetic evidence mode")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
get_filename_component(root "${LUNA_COMPILED_EVIDENCE_TEST_ROOT}/session-${nonce}" ABSOLUTE)
if(EXISTS "${root}")
    message(FATAL_ERROR "synthetic evidence directory already exists")
endif()

function(bundle_fixture directory cycles eol)
    if(LUNA_COMPILED_EVIDENCE_TEST_MODE STREQUAL pinned)
        luna_compiled_pinned_bundle_fixture("${directory}" "${cycles}" "${eol}")
    else()
        luna_compiled_bundle_fixture("${directory}" "${cycles}" "${eol}")
    endif()
endfunction()

function(package_evidence)
    if(LUNA_COMPILED_EVIDENCE_TEST_MODE STREQUAL pinned)
        luna_package_compiled_pinned_evidence()
    else()
        luna_package_compiled_evidence()
    endif()
endfunction()

function(verify_evidence directory)
    if(LUNA_COMPILED_EVIDENCE_TEST_MODE STREQUAL pinned)
        luna_verify_compiled_pinned_evidence("${directory}")
    else()
        luna_verify_compiled_evidence("${directory}")
    endif()
endfunction()

function(snapshot_tree directory result)
    file(GLOB_RECURSE files LIST_DIRECTORIES FALSE "${directory}/*")
    set(hashes "")
    foreach(path IN LISTS files)
        file(SHA256 "${path}" hash)
        string(APPEND hashes "${path}:${hash}\n")
    endforeach()
    set(${result} "${hashes}" PARENT_SCOPE)
endfunction()

function(export_fixture directory cycles eol)
    bundle_fixture("${directory}/bundle" "${cycles}" "${eol}")
    set(${anchor}_BUNDLE_DIR "${directory}/bundle")
    set(${anchor}_OUTPUT_DIR "${directory}/evidence")
    string(REPEAT a 40 ${anchor}_EXPECTED_COMMIT)
    file(SHA256 "${directory}/bundle/manifest.csv" ${anchor}_EXPECTED_MANIFEST_SHA256)
    file(GLOB files "${directory}/bundle/*")
    set(before "")
    foreach(path IN LISTS files)
        file(SHA256 "${path}" hash)
        string(APPEND before "${path}:${hash}\n")
    endforeach()
    package_evidence()
    file(GLOB_RECURSE source_files LIST_DIRECTORIES FALSE "${directory}/evidence/source/*")
    list(LENGTH source_files source_count)
    if(NOT source_count EQUAL expected_sources)
        message(FATAL_ERROR "evidence source inventory size changed")
    endif()
    set(after "")
    foreach(path IN LISTS files)
        file(SHA256 "${path}" hash)
        string(APPEND after "${path}:${hash}\n")
    endforeach()
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "evidence export modified input observation bytes")
    endif()
endfunction()

if(DEFINED EVIDENCE_TEST_CASE)
    if(EVIDENCE_TEST_CASE MATCHES "^(existing_output|nested_output|missing_parent|missing_anchor|wrong_anchor|bad_input|wrong_input_mode)$")
        if(EVIDENCE_TEST_CASE STREQUAL wrong_input_mode)
            if(LUNA_COMPILED_EVIDENCE_TEST_MODE STREQUAL pinned)
                luna_compiled_bundle_fixture("${root}/bundle" 1)
            else()
                luna_compiled_pinned_bundle_fixture("${root}/bundle" 1)
            endif()
        else()
            bundle_fixture("${root}/bundle" 1 LF)
        endif()
        set(${anchor}_BUNDLE_DIR "${root}/bundle")
        set(${anchor}_OUTPUT_DIR "${root}/evidence")
        string(REPEAT a 40 ${anchor}_EXPECTED_COMMIT)
        file(SHA256 "${root}/bundle/manifest.csv" ${anchor}_EXPECTED_MANIFEST_SHA256)
        if(EVIDENCE_TEST_CASE STREQUAL existing_output)
            file(MAKE_DIRECTORY "${root}/evidence")
            file(WRITE "${root}/evidence/sentinel" "retained\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL nested_output)
            set(${anchor}_OUTPUT_DIR "${root}/bundle/nested")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_parent)
            set(${anchor}_OUTPUT_DIR "${root}/absent/evidence")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_anchor)
            unset(${anchor}_EXPECTED_MANIFEST_SHA256)
        elseif(EVIDENCE_TEST_CASE STREQUAL wrong_anchor)
            string(REPEAT b 64 ${anchor}_EXPECTED_MANIFEST_SHA256)
        elseif(EVIDENCE_TEST_CASE STREQUAL bad_input)
            file(APPEND "${root}/bundle/process-1-O0.csv" "# changed\n")
        endif()
        package_evidence()
    else()
        export_fixture("${root}" 1 LF)
        set(directory "${root}/evidence")
        file(READ "${directory}/evidence.csv" index)
        if(EVIDENCE_TEST_CASE STREQUAL wrong_reader_mode)
            if(LUNA_COMPILED_EVIDENCE_TEST_MODE STREQUAL pinned)
                luna_verify_compiled_evidence("${directory}")
            else()
                luna_verify_compiled_pinned_evidence("${directory}")
            endif()
        elseif(EVIDENCE_TEST_CASE STREQUAL controller_hash)
            file(APPEND "${directory}/source/benchmarks/fragment_thread_affinity.h" "// changed\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_controller)
            file(RENAME "${directory}/source/benchmarks/fragment_thread_affinity.h" "${root}/retained-controller.h")
        elseif(EVIDENCE_TEST_CASE STREQUAL source_hash)
            file(APPEND "${directory}/source/tests/compiled_fragment_bundle.cmake" "# changed\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL record_hash)
            file(APPEND "${directory}/bundle/process-1-O0.csv" "# changed\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_record)
            file(RENAME "${directory}/bundle/process-1-O0.csv" "${root}/retained-record.csv")
        elseif(EVIDENCE_TEST_CASE STREQUAL symlink_record)
            file(RENAME "${directory}/bundle/process-1-O0.csv" "${root}/retained-record.csv")
            file(CREATE_LINK "${root}/retained-record.csv" "${directory}/bundle/process-1-O0.csv" SYMBOLIC)
        elseif(EVIDENCE_TEST_CASE STREQUAL path_escape)
            string(REPLACE "bundle/manifest.csv," "../bundle/manifest.csv," index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL duplicate_row)
            string(APPEND index "bundle/manifest.csv,aaaaaaaa\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL missing_row)
            string(REGEX REPLACE "bundle/manifest.csv,[0-9a-f]+\n" "" index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL duplicate_metadata)
            string(APPEND index "# approval=none\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL approval_claim)
            string(REPLACE "approval=none" "approval=approved" index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL manifest_anchor)
            string(REPEAT b 64 hash)
            string(REGEX REPLACE "(# bundle_manifest_sha256=)[0-9a-f]+" "\\1${hash}" index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL bundle_commit)
            string(REPEAT b 40 commit)
            string(REGEX REPLACE "(# bundle_git_commit=)[0-9a-f]+" "\\1${commit}" index "${index}")
        elseif(EVIDENCE_TEST_CASE STREQUAL semicolon)
            string(APPEND index ";\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL extra_file)
            file(WRITE "${directory}/source/unlisted.txt" "synthetic\n")
        elseif(EVIDENCE_TEST_CASE STREQUAL expected_index)
            string(REPEAT b 64 ${anchor}_EXPECTED_INDEX_SHA256)
        elseif(EVIDENCE_TEST_CASE STREQUAL expected_commit)
            string(REPEAT b 40 ${anchor}_EXPECTED_COMMIT)
        else()
            message(FATAL_ERROR "unknown synthetic evidence rejection")
        endif()
        file(WRITE "${directory}/evidence.csv" "${index}")
        verify_evidence("${directory}")
    endif()
    message(FATAL_ERROR "invalid evidence fixture was accepted")
endif()

foreach(configuration IN ITEMS "1/LF" "1/CRLF" "2/LF" "10/LF")
    string(REPLACE "/" ";" fields "${configuration}")
    list(GET fields 0 cycles)
    list(GET fields 1 eol)
    export_fixture("${root}/${cycles}-${eol}" "${cycles}" "${eol}")
endforeach()
# Migrate by copying, not moving/deleting an observation. Verify with trusted
# checkout code, then run only the known exact-byte copy of our own reader.
file(COPY "${root}/1-LF/evidence" DESTINATION "${root}/relocated")
set(directory "${root}/relocated/evidence")
file(SHA256 "${directory}/evidence.csv" ${anchor}_EXPECTED_INDEX_SHA256)
string(REPEAT a 40 ${anchor}_EXPECTED_COMMIT)
snapshot_tree("${directory}" before)
verify_evidence("${directory}")
snapshot_tree("${directory}" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "evidence byte verifier modified relocated files")
endif()
file(SHA256 "${directory}/bundle/manifest.csv" manifest_hash)
execute_process(COMMAND "${CMAKE_COMMAND}" "${author_warning_error}"
        "-D${bundle_anchor}_DIR=${directory}/bundle"
        "-D${bundle_anchor}_EXPECTED_COMMIT=${${anchor}_EXPECTED_COMMIT}"
        "-D${bundle_anchor}_EXPECTED_MANIFEST_SHA256=${manifest_hash}"
        -P "${directory}/source/tests/${reader}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 0 OR NOT errors STREQUAL "")
    message(FATAL_ERROR "trusted copied reader failed after relocation: ${output}${errors}")
endif()
# A rehashed archived script is data to the byte verifier, not executable code.
unset(${anchor}_EXPECTED_INDEX_SHA256)
file(WRITE "${directory}/source/tests/compiled_fragment_bundle.cmake"
    "message(FATAL_ERROR \"ARCHIVED_CODE_EXECUTED\")\n")
file(SHA256 "${directory}/source/tests/compiled_fragment_bundle.cmake" hash)
file(READ "${directory}/evidence.csv" index)
string(REGEX REPLACE "(source/tests/compiled_fragment_bundle[.]cmake,)[0-9a-f]+" "\\1${hash}" index "${index}")
file(WRITE "${directory}/evidence.csv" "${index}")
file(SHA256 "${directory}/evidence.csv" before)
verify_evidence("${directory}")
file(SHA256 "${directory}/evidence.csv" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "evidence byte verifier modified index")
endif()
set(rejections "existing_output|already exists" "nested_output|inside the input"
    "missing_parent|output parent" "missing_anchor|requires EXPECTED_MANIFEST"
    "wrong_anchor|expected manifest SHA-256 mismatch" "bad_input|raw-file SHA-256"
    "source_hash|file SHA-256" "record_hash|file SHA-256" "missing_record|non-symlink file"
    "path_escape|noncanonical path" "duplicate_row|invalid checksum row"
    "missing_row|noncanonical path" "duplicate_metadata|exactly once"
    "approval_claim|approval claim" "manifest_anchor|manifest anchor mismatch"
    "bundle_commit|bundle metadata anchor mismatch"
    "semicolon|semicolon" "extra_file|unlisted" "expected_index|expected index SHA-256"
    "expected_commit|expected commit mismatch" "wrong_input_mode|unsupported protocol"
    "wrong_reader_mode|unsupported protocol")
if(LUNA_COMPILED_EVIDENCE_TEST_MODE STREQUAL pinned)
    list(APPEND rejections "controller_hash|file SHA-256" "missing_controller|non-symlink file")
endif()
if(UNIX)
    list(APPEND rejections "symlink_record|non-symlink file")
endif()
foreach(test IN LISTS rejections)
    string(REPLACE "|" ";" fields "${test}")
    list(GET fields 0 name)
    list(GET fields 1 expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "${author_warning_error}" "-DEVIDENCE_TEST_CASE=${name}"
            "-DLUNA_COMPILED_EVIDENCE_TEST_ROOT=${root}/children-${name}"
            "-DLUNA_COMPILED_EVIDENCE_TEST_MODE=${LUNA_COMPILED_EVIDENCE_TEST_MODE}"
            -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT status EQUAL 1 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "synthetic evidence rejection ${name} failed (${status}): ${output}${errors}")
    endif()
    if(name MATCHES "^(nested_output|missing_parent|missing_anchor|wrong_anchor|bad_input|wrong_input_mode)$")
        file(GLOB sessions LIST_DIRECTORIES TRUE "${root}/children-${name}/session-*")
        foreach(session IN LISTS sessions)
            if(EXISTS "${session}/evidence" OR EXISTS "${session}/bundle/nested" OR EXISTS "${session}/absent")
                message(FATAL_ERROR "failed evidence export created output")
            endif()
        endforeach()
    endif()
    file(GLOB sentinel "${root}/children-existing_output/session-*/evidence/sentinel")
    foreach(path IN LISTS sentinel)
        file(READ "${path}" retained)
        if(NOT retained STREQUAL "retained\n")
            message(FATAL_ERROR "existing output sentinel was overwritten")
        endif()
    endforeach()
endforeach()
message(STATUS "Compiled Fragment ${LUNA_COMPILED_EVIDENCE_TEST_MODE} evidence tests: synthetic files, relocation, archived code inert; no timing executable")
