cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_protocol.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_fixture.cmake")
if(NOT DEFINED LUNA_PYTHON_EXECUTABLE OR NOT DEFINED LUNA_COMPILED_SUMMARY_TEST_ROOT)
    message(FATAL_ERROR "summary test requires Python and a build-tree fixture root")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
set(root "${LUNA_COMPILED_SUMMARY_TEST_ROOT}/session-${nonce}")
if(EXISTS "${root}")
    message(FATAL_ERROR "summary fixture directory already exists")
endif()
set(tool "${CMAKE_CURRENT_LIST_DIR}/../tools/summarize_compiled_fragment_bundle.py")
string(REPEAT a 40 commit)

function(run_summary directory result)
    execute_process(COMMAND "${LUNA_PYTHON_EXECUTABLE}" -B "${tool}"
            --bundle "${directory}" --cmake "${CMAKE_COMMAND}" ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
    if(NOT status EQUAL 0 OR NOT errors STREQUAL "")
        message(FATAL_ERROR "synthetic summary failed (${status}): ${output}${errors}")
    endif()
    string(JSON protocol GET "${output}" protocol)
    string(JSON approval GET "${output}" approval)
    if(NOT protocol STREQUAL "luna.compiled-fragment-summary.v1" OR NOT approval STREQUAL none)
        message(FATAL_ERROR "summary protocol/approval mismatch")
    endif()
    set(${result} "${output}" PARENT_SCOPE)
endfunction()

function(assert_json report expected)
    string(JSON actual GET "${report}" ${ARGN})
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "summary field ${ARGN}: expected ${expected}, got ${actual}")
    endif()
endfunction()

function(snapshot directory result)
    file(GLOB files "${directory}/*")
    set(hashes "")
    foreach(path IN LISTS files)
        file(SHA256 "${path}" hash)
        string(APPEND hashes "${path}:${hash}\n")
    endforeach()
    set(${result} "${hashes}" PARENT_SCOPE)
endfunction()

# Zero is valid; line endings change byte anchors, not descriptive statistics.
foreach(eol IN ITEMS LF CRLF)
    luna_compiled_bundle_fixture("${root}/${eol}" 2 "${eol}")
    file(SHA256 "${root}/${eol}/manifest.csv" hash)
    snapshot("${root}/${eol}" before)
    run_summary("${root}/${eol}" report --expected-commit "${commit}" --expected-manifest-sha256 "${hash}")
    assert_json("${report}" "${hash}" input_manifest_sha256)
    assert_json("${report}" 12 profiles O0 independent_processes)
    assert_json("${report}" 12 profiles O0 cases_process_medians_ns_per_op plain count)
    assert_json("${report}" 0.0 profiles O0 cases_process_medians_ns_per_op plain median)
    string(JSON count LENGTH "${report}" processes)
    if(NOT count EQUAL 36)
        message(FATAL_ERROR "summary lost independent processes")
    endif()
    snapshot("${root}/${eol}" after)
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "summary modified observation files")
    endif()
endforeach()

# Five small and four large samples per process distinguish process medians
# from a pooled-round median. Different integer widths catch lexical sorting.
set(directory "${root}/nonzero")
luna_compiled_bundle_fixture("${directory}" 1)
file(READ "${directory}/manifest.csv" manifest)
set(combined "process,cycle,block,profile_position,profile,round,position,case,ns_per_op,calls,checksum\n")
luna_compiled_series_schedule(1 schedule)
set(process 0)
foreach(item IN LISTS schedule)
    math(EXPR process "${process} + 1")
    string(REPLACE "," ";" fields "${item}")
    list(GET fields 3 profile)
    set(filename "process-${process}-${profile}.csv")
    file(SHA256 "${directory}/${filename}" old_hash)
    file(READ "${directory}/${filename}" raw)
    foreach(key IN ITEMS compile_encode_decode_ms verified_load_jit_ms discovery_binding_ms)
        string(REPLACE "# ${key}=0.000" "# ${key}=${process}.100" raw "${raw}")
    endforeach()
    string(REPLACE "\n" ";" lines "${raw}")
    set(updated "")
    foreach(line IN LISTS lines)
        if(line MATCHES "^([1-9]),([1-9]),([^,]+),0[.]0,(.*)$")
            set(round "${CMAKE_MATCH_1}")
            set(position "${CMAKE_MATCH_2}")
            set(case "${CMAKE_MATCH_3}")
            set(counters "${CMAKE_MATCH_4}")
            if(round LESS 3)
                set(time "${process}.1")
            elseif(round LESS 6)
                set(time "${process}.2")
            else()
                math(EXPR large "1000000 + ${process}")
                set(time "${large}.0")
            endif()
            set(line "${round},${position},${case},${time},${counters}")
            string(APPEND combined "${process},${item},${line}\n")
        endif()
        if(NOT line STREQUAL "")
            string(APPEND updated "${line}\n")
        endif()
    endforeach()
    file(WRITE "${directory}/${filename}" "${updated}")
    file(SHA256 "${directory}/${filename}" new_hash)
    string(REPLACE "${filename},${old_hash}" "${filename},${new_hash}" manifest "${manifest}")
endforeach()
file(WRITE "${directory}/samples.csv" "${combined}")
file(SHA256 "${directory}/samples.csv" hash)
string(REGEX REPLACE "(# combined_sha256=)[0-9a-f]+" "\\1${hash}" manifest "${manifest}")
file(WRITE "${directory}/manifest.csv" "${manifest}")
snapshot("${directory}" before)
run_summary("${directory}" report)
assert_json("${report}" 1.1 processes 0 cases_ns_per_op plain min)
assert_json("${report}" 1.2 processes 0 cases_ns_per_op plain median)
assert_json("${report}" 1000001.0 processes 0 cases_ns_per_op plain max)
assert_json("${report}" 9 processes 0 cases_ns_per_op plain count)
assert_json("${report}" 6 profiles O0 cases_process_medians_ns_per_op plain count)
assert_json("${report}" 10.2 profiles O0 cases_process_medians_ns_per_op plain median)
assert_json("${report}" 8.7 profiles O2 cases_process_medians_ns_per_op plain median)
assert_json("${report}" 10.100 profiles O0 setup_single_observations_ms verified_load_jit_ms median)
snapshot("${directory}" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "summary modified nonzero observation files")
endif()

string(REPEAT b 40 wrong_commit)
string(REPEAT b 64 wrong_hash)
set(rejections "commit|expected commit mismatch" "manifest|expected manifest SHA-256 mismatch"
    "corrupt|raw-file SHA-256 mismatch" "missing_cmake|compiled Fragment summary:")
foreach(rejection IN LISTS rejections)
    string(REPLACE "|" ";" fields "${rejection}")
    list(GET fields 0 name)
    list(GET fields 1 expected)
    set(extra "")
    set(cmake "${CMAKE_COMMAND}")
    if(name STREQUAL "commit")
        set(extra --expected-commit "${wrong_commit}")
    elseif(name STREQUAL "manifest")
        set(extra --expected-manifest-sha256 "${wrong_hash}")
    elseif(name STREQUAL "corrupt")
        file(APPEND "${root}/LF/process-1-O0.csv" "# changed\n")
    elseif(name STREQUAL "missing_cmake")
        set(cmake "${root}/no-such-cmake")
    endif()
    execute_process(COMMAND "${LUNA_PYTHON_EXECUTABLE}" -B "${tool}"
            --bundle "${root}/LF" --cmake "${cmake}" ${extra}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
    if(NOT status EQUAL 1 OR NOT output STREQUAL "" OR NOT errors MATCHES "${expected}" OR errors MATCHES "Traceback")
        string(SUBSTRING "${output}" 0 2048 preview)
        message(FATAL_ERROR "summary rejection ${name} failed (${status}): ${preview}${errors}")
    endif()
endforeach()
message(STATUS "Compiled Fragment summary: decimal statistics, process aggregation, read-only files and fail-closed reporting; no timing probe")
