cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_protocol.cmake")

# Synthetic protocol records only. This default test never invokes a timing
# binary or creates an observation bundle.
function(fixture profile result)
    file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/../benchmarks/compiled_fragment_benchmark.cpp" probe_hash)
    set(workload_input "")
    foreach(path IN ITEMS host/luna.package host/src/effects.luna luna.lock luna.workspace
                          plugin/luna.package plugin/src/effects.luna)
        file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/../benchmarks/compiled_fragment/${path}" hash)
        string(APPEND workload_input "${path}:${hash}\n")
    endforeach()
    string(SHA256 workload_hash "${workload_input}")
    string(REPEAT a 64 host_hash)
    string(REPEAT b 64 plugin_hash)
    set(output "# protocol=luna.compiled-fragment-cost.v2\n# git_commit=synthetic-test-only\n")
    string(APPEND output "# probe_sha256=${probe_hash}\n# workload_sha256=${workload_hash}\n")
    string(APPEND output "# build_type=synthetic\n# compiler=synthetic\n# cxx=201703,llvm=synthetic\n")
    string(APPEND output "# target=synthetic\n# data_layout=synthetic\n")
    string(APPEND output "# host_container_sha256=${host_hash}\n# plugin_container_sha256=${plugin_hash}\n")
    string(APPEND output "# moonir_optimization=O2,llvm_optimization=${profile}\n# orc_codegen=default\n")
    string(APPEND output "# materialization_key=luna.verified-moon-jit.v1:llvm=synthetic:ir=${profile}:orc=default\n")
    string(APPEND output "# candidate_count=4,host_order=resume_a/resume_b/resume_c/resume_d\n")
    string(APPEND output "# correctness_checks=320,runtime_alive_during_samples=no\n")
    foreach(key IN ITEMS compile_encode_decode_ms verified_load_jit_ms discovery_binding_ms)
        string(APPEND output "# ${key}=0.000\n")
    endforeach()
    string(APPEND output "# iterations=3,warmup=3,rounds=9\n# affinity=uncontrolled,power_policy=uncontrolled\n")
    string(APPEND output "# timed_harness=case_branch+input_modulo+JIT_call+checksum\n")
    string(APPEND output "round,position,case,ns_per_op,calls,checksum\n")
    set(cases plain private_erased static_resume static_discard dynamic_none dynamic_one
        dynamic_chain_2 dynamic_chain_4 dynamic_override_none)
    foreach(sample RANGE 0 80)
        math(EXPR round "${sample} / 9 + 1")
        math(EXPR position "${sample} % 9 + 1")
        math(EXPR index "(${position} - 1 + (${round} - 1) * 4) % 9")
        list(GET cases ${index} name)
        set(checksum 120)
        if(index EQUAL 3)
            set(checksum 18)
        endif()
        string(APPEND output "${round},${position},${name},0.0,6,${checksum}\n")
    endforeach()
    string(APPEND output "# verified_samples=81,position_balanced=yes\n")
    set(${result} "${output}" PARENT_SCOPE)
endfunction()

if(DEFINED TEST_CASE)
    fixture(O0 output)
    luna_compiled_series_schedule(1 schedule)
    if(TEST_CASE STREQUAL duplicate_metadata)
        string(APPEND output "# target=synthetic\n")
    elseif(TEST_CASE STREQUAL digest_suffix)
        string(REPEAT a 64 hash)
        string(REPLACE "${hash}" "${hash}suffix" output "${output}")
    elseif(TEST_CASE STREQUAL changed_source)
        luna_compiled_probe_metadata("${output}" probe_sha256 hash)
        string(REPEAT c 64 changed)
        string(REPLACE "${hash}" "${changed}" output "${output}")
    elseif(TEST_CASE STREQUAL wrong_profile)
        luna_validate_compiled_probe("${output}" 3 O2)
    elseif(TEST_CASE STREQUAL wrong_key)
        string(REPLACE "ir=O0" "ir=O3" output "${output}")
    elseif(TEST_CASE STREQUAL wrong_checksum)
        string(REPLACE "1,1,plain,0.0,6,120" "1,1,plain,0.0,6,121" output "${output}")
    elseif(TEST_CASE STREQUAL wrong_calls)
        string(REPLACE ",6,120" ",7,120" output "${output}")
    elseif(TEST_CASE STREQUAL extra_sample)
        string(APPEND output "1,1,plain,0.0,6,120\n")
    elseif(TEST_CASE STREQUAL missing_header)
        string(REPLACE "round,position,case,ns_per_op,calls,checksum\n" "" output "${output}")
    elseif(TEST_CASE STREQUAL duplicate_header)
        string(APPEND output "round,position,case,ns_per_op,calls,checksum\n")
    elseif(TEST_CASE STREQUAL invalid_footer)
        string(REPLACE "verified_samples=81" "verified_samples=80" output "${output}")
    elseif(TEST_CASE STREQUAL changed_artifact OR TEST_CASE STREQUAL changed_build)
        luna_compiled_series_identity("${output}" O0)
        fixture(O2 output)
        if(TEST_CASE STREQUAL changed_artifact)
            string(REPEAT a 64 hash)
            string(REPEAT c 64 changed)
            string(REPLACE "${hash}" "${changed}" output "${output}")
        else()
            string(REPLACE "compiler=synthetic" "compiler=different" output "${output}")
        endif()
        luna_validate_compiled_probe("${output}" 3 O2)
        luna_compiled_series_identity("${output}" O2)
    elseif(TEST_CASE STREQUAL repeated_profile)
        list(REMOVE_AT schedule 1)
        list(INSERT schedule 1 "1,1,2,O0")
        luna_validate_compiled_series_schedule("${schedule}" 1)
    elseif(TEST_CASE STREQUAL repeated_permutation)
        list(REMOVE_AT schedule 3 4 5)
        list(INSERT schedule 3 "1,2,1,O0" "1,2,2,O2" "1,2,3,O3")
        luna_validate_compiled_series_schedule("${schedule}" 1)
    elseif(TEST_CASE STREQUAL missing_process)
        list(REMOVE_AT schedule 17)
        luna_validate_compiled_series_schedule("${schedule}" 1)
    elseif(TEST_CASE STREQUAL wrong_process_position)
        list(REMOVE_AT schedule 0)
        list(INSERT schedule 0 "1,1,2,O0")
        luna_validate_compiled_series_schedule("${schedule}" 1)
    elseif(TEST_CASE STREQUAL invalid_cycles)
        luna_compiled_series_schedule(11 schedule)
    elseif(TEST_CASE STREQUAL noncanonical_integer)
        luna_validate_compiled_probe("${output}" 03 O0)
    elseif(TEST_CASE STREQUAL trailing_text)
        string(APPEND output "not-a-record\n")
    elseif(TEST_CASE STREQUAL occupied_output)
        set(LUNA_COMPILED_PROBE_EXECUTABLE "${CMAKE_COMMAND}")
        set(LUNA_COMPILED_SERIES_OUTPUT_DIR "${CMAKE_CURRENT_LIST_DIR}")
        include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_series.cmake")
    else()
        message(FATAL_ERROR "unknown synthetic test case")
    endif()
    luna_validate_compiled_probe("${output}" 3 O0)
    message(FATAL_ERROR "damaged fixture was accepted")
endif()

foreach(profile IN ITEMS O0 O2 O3)
    fixture("${profile}" output)
    luna_validate_compiled_probe("${output}" 3 "${profile}")
    luna_compiled_series_identity("${output}" "${profile}")
    string(REPLACE "\n" "\r\n" crlf "${output}")
    luna_validate_compiled_probe("${crlf}" 3 "${profile}")
endforeach()
foreach(cycles IN ITEMS 1 2 6 10)
    luna_compiled_series_schedule("${cycles}" schedule)
    luna_validate_compiled_series_schedule("${schedule}" "${cycles}")
endforeach()
luna_compiled_series_schedule(2 schedule)
list(GET schedule 19 rotated)
if(NOT rotated STREQUAL "2,1,2,O3")
    message(FATAL_ERROR "series cycle did not rotate permutation-block order")
endif()
foreach(test IN ITEMS "duplicate_metadata|exactly once" "digest_suffix|SHA-256"
        "changed_source|metadata mismatch"
        "wrong_profile|metadata mismatch" "wrong_key|configuration identity"
        "wrong_checksum|checksum mismatch" "wrong_calls|checksum mismatch"
        "extra_sample|checksum mismatch" "missing_header|one CSV header"
        "duplicate_header|header is not before" "invalid_footer|metadata mismatch"
        "changed_artifact|changed common identity" "changed_build|changed common identity"
        "repeated_profile|repeated a profile" "repeated_permutation|repeated a permutation"
        "missing_process|process count" "wrong_process_position|changed order"
        "invalid_cycles|cycles must" "noncanonical_integer|validation configuration"
        "trailing_text|unexpected compiled" "occupied_output|already exists")
    string(REPLACE "|" ";" fields "${test}")
    list(GET fields 0 name)
    list(GET fields 1 expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -Werror=dev "-DTEST_CASE=${name}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE status OUTPUT_VARIABLE child_output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT status EQUAL 1 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "synthetic rejection ${name} failed (${status}): ${child_output}${errors}")
    endif()
endforeach()
message(STATUS "Compiled Fragment series protocol: synthetic records and schedule rejection; no timing probe invoked")
