cmake_minimum_required(VERSION 3.20)

# Synthetic records only: zero latency is deliberately valid. Never runs JIT.
function(luna_compiled_probe_fixture profile result)
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmarks/compiled_fragment_benchmark.cpp" probe_hash)
    set(workload_input "")
    foreach(path IN ITEMS host/luna.package host/src/effects.luna luna.lock luna.workspace
                          plugin/luna.package plugin/src/effects.luna)
        file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmarks/compiled_fragment/${path}" hash)
        string(APPEND workload_input "${path}:${hash}\n")
    endforeach()
    string(SHA256 workload_hash "${workload_input}")
    string(REPEAT a 64 host_hash)
    string(REPEAT b 64 plugin_hash)
    set(output "# protocol=luna.compiled-fragment-cost.v2\n# git_commit=synthetic-test-only\n")
    string(APPEND output "# probe_sha256=${probe_hash}\n# workload_sha256=${workload_hash}\n")
    string(APPEND output "# build_type=synthetic\n# compiler=synthetic\n# cxx=201703,llvm=synthetic\n")
    string(APPEND output "# target=synthetic\n# data_layout=synthetic\n")
    string(APPEND output "# host_container_sha256=${host_hash}\n# plugin_container_sha256=${plugin_hash}\n")
    string(APPEND output "# moonir_optimization=O2,llvm_optimization=${profile}\n# orc_codegen=default\n")
    string(APPEND output "# materialization_key=luna.verified-moon-jit.v1:llvm=synthetic:ir=${profile}:orc=default\n")
    string(APPEND output "# candidate_count=4,host_order=resume_a/resume_b/resume_c/resume_d\n")
    string(APPEND output "# correctness_checks=320,runtime_alive_during_samples=no\n")
    foreach(key IN ITEMS compile_encode_decode_ms verified_load_jit_ms discovery_binding_ms)
        string(APPEND output "# ${key}=0.000\n")
    endforeach()
    string(APPEND output "# iterations=3,warmup=3,rounds=9\n# affinity=uncontrolled,power_policy=uncontrolled\n")
    string(APPEND output "# timed_harness=case_branch+input_modulo+JIT_call+checksum\n")
    string(APPEND output "round,position,case,ns_per_op,calls,checksum\n")
    set(cases plain private_erased static_resume static_discard dynamic_none dynamic_one
        dynamic_chain_2 dynamic_chain_4 dynamic_override_none)
    foreach(sample RANGE 0 80)
        math(EXPR round "${sample} / 9 + 1")
        math(EXPR position "${sample} % 9 + 1")
        math(EXPR index "(${position} - 1 + (${round} - 1) * 4) % 9")
        list(GET cases ${index} name)
        set(checksum 120)
        if(index EQUAL 3)
            set(checksum 18)
        endif()
        string(APPEND output "${round},${position},${name},0.0,6,${checksum}\n")
    endforeach()
    string(APPEND output "# verified_samples=81,position_balanced=yes\n")
    set(${result} "${output}" PARENT_SCOPE)
endfunction()
