cmake_minimum_required(VERSION 3.20)

# Pure validation: never starts a probe, writes observations or checks latency.
function(luna_compiled_probe_metadata output key result)
    string(REPLACE "\r\n" "\n" normalized "${output}")
    string(REPLACE "\n" ";" lines "${normalized}")
    set(count 0)
    foreach(line IN LISTS lines)
        if(line MATCHES "^# ${key}=(.*)$")
            set(value "${CMAKE_MATCH_1}")
            math(EXPR count "${count} + 1")
        endif()
    endforeach()
    if(NOT count EQUAL 1 OR value STREQUAL "")
        message(FATAL_ERROR "compiled probe metadata must occur exactly once: ${key}")
    endif()
    set(${result} "${value}" PARENT_SCOPE)
endfunction()

function(luna_validate_compiled_probe output iterations profile)
    if(NOT iterations MATCHES "^[1-9][0-9]*$" OR iterations LESS 1 OR iterations GREATER 10000000 OR
       NOT profile MATCHES "^O[023]$")
        message(FATAL_ERROR "invalid compiled probe validation configuration")
    endif()
    string(REPLACE "\r\n" "\n" normalized "${output}")
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmarks/compiled_fragment_benchmark.cpp" probe_hash)
    set(workload_input "")
    foreach(path IN ITEMS host/luna.package host/src/effects.luna luna.lock luna.workspace
                          plugin/luna.package plugin/src/effects.luna)
        file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmarks/compiled_fragment/${path}" hash)
        string(APPEND workload_input "${path}:${hash}\n")
    endforeach()
    string(SHA256 workload_hash "${workload_input}")
    foreach(required IN ITEMS "protocol=luna.compiled-fragment-cost.v2"
            "probe_sha256=${probe_hash}" "workload_sha256=${workload_hash}"
            "moonir_optimization=O2,llvm_optimization=${profile}" "orc_codegen=default"
            "candidate_count=4,host_order=resume_a/resume_b/resume_c/resume_d"
            "correctness_checks=320,runtime_alive_during_samples=no"
            "affinity=uncontrolled,power_policy=uncontrolled"
            "timed_harness=case_branch+input_modulo+JIT_call+checksum"
            "verified_samples=81,position_balanced=yes")
        string(REGEX REPLACE "=.*$" "" key "${required}")
        luna_compiled_probe_metadata("${normalized}" "${key}" value)
        if(NOT "${key}=${value}" STREQUAL required)
            message(FATAL_ERROR "compiled probe metadata mismatch: ${required}")
        endif()
    endforeach()
    foreach(key IN ITEMS git_commit build_type compiler cxx target data_layout)
        luna_compiled_probe_metadata("${normalized}" "${key}" value)
    endforeach()
    luna_compiled_probe_metadata("${normalized}" cxx dialect)
    if(NOT dialect MATCHES "^[0-9]+,llvm=([^\r\n]+)$")
        message(FATAL_ERROR "compiled probe lost LLVM/dialect identity")
    endif()
    set(materialization_key "luna.verified-moon-jit.v1:llvm=${CMAKE_MATCH_1}:ir=${profile}:orc=default")
    luna_compiled_probe_metadata("${normalized}" materialization_key value)
    if(NOT value STREQUAL materialization_key)
        message(FATAL_ERROR "compiled probe JIT configuration identity mismatch")
    endif()
    foreach(key IN ITEMS host_container_sha256 plugin_container_sha256)
        luna_compiled_probe_metadata("${normalized}" "${key}" value)
        string(LENGTH "${value}" length)
        if(NOT value MATCHES "^[0-9a-f]+$" OR NOT length EQUAL 64)
            message(FATAL_ERROR "compiled probe lost artifact SHA-256: ${key}")
        endif()
    endforeach()
    foreach(key IN ITEMS compile_encode_decode_ms verified_load_jit_ms discovery_binding_ms)
        luna_compiled_probe_metadata("${normalized}" "${key}" value)
        if(NOT value MATCHES "^[0-9]+[.][0-9]+$")
            message(FATAL_ERROR "compiled probe lost setup observation: ${key}")
        endif()
    endforeach()
    set(warmup ${iterations})
    if(warmup GREATER 1000)
        set(warmup 1000)
    endif()
    luna_compiled_probe_metadata("${normalized}" iterations value)
    if(NOT value STREQUAL "${iterations},warmup=${warmup},rounds=9")
        message(FATAL_ERROR "compiled probe sampling configuration mismatch")
    endif()
    math(EXPR calls "${iterations} + ${warmup}")
    set(base_checksum 0)
    foreach(count IN ITEMS ${iterations} ${warmup})
        math(EXPR full "${count} / 1024")
        math(EXPR remainder "${count} % 1024")
        math(EXPR checksum "3 * (${full} * 523776 + ${remainder} * (${remainder} - 1) / 2)")
        math(EXPR base_checksum "${base_checksum} + ${checksum}")
    endforeach()
    math(EXPR resumed_checksum "${base_checksum} + 17 * ${calls}")
    set(cases plain private_erased static_resume static_discard dynamic_none dynamic_one
        dynamic_chain_2 dynamic_chain_4 dynamic_override_none)
    string(REPLACE "\n" ";" lines "${normalized}")
    set(samples 0)
    set(headers 0)
    foreach(line IN LISTS lines)
        if(line MATCHES "^[0-9]")
            math(EXPR round "${samples} / 9 + 1")
            math(EXPR position "${samples} % 9 + 1")
            math(EXPR case_index "(${position} - 1 + (${round} - 1) * 4) % 9")
            list(GET cases ${case_index} case_name)
            set(checksum ${resumed_checksum})
            if(case_index EQUAL 3)
                set(checksum ${base_checksum})
            endif()
            if(NOT line MATCHES "^${round},${position},${case_name},[0-9]+[.][0-9],${calls},${checksum}$")
                message(FATAL_ERROR "compiled schedule/calls/checksum mismatch: ${line}")
            endif()
            set(visit "${case_index}_${position}")
            if(DEFINED seen_${visit})
                message(FATAL_ERROR "compiled probe repeated case/position: ${visit}")
            endif()
            set(seen_${visit} TRUE)
            math(EXPR samples "${samples} + 1")
        elseif(line STREQUAL "round,position,case,ns_per_op,calls,checksum")
            math(EXPR headers "${headers} + 1")
            if(NOT samples EQUAL 0)
                message(FATAL_ERROR "compiled CSV header is not before samples")
            endif()
        elseif(NOT line STREQUAL "" AND NOT line MATCHES "^#")
            message(FATAL_ERROR "unexpected compiled probe output: ${line}")
        endif()
    endforeach()
    if(NOT samples EQUAL 81 OR NOT headers EQUAL 1)
        message(FATAL_ERROR "compiled probe needs exactly 81 samples and one CSV header")
    endif()
endfunction()

# Complete permutation blocks. Cycles rotate block order, not profile policy.
function(luna_compiled_series_schedule cycles result)
    if(NOT cycles MATCHES "^[1-9][0-9]*$" OR cycles LESS 1 OR cycles GREATER 10)
        message(FATAL_ERROR "compiled series cycles must be 1..10")
    endif()
    set(permutations "O0/O2/O3" "O0/O3/O2" "O2/O0/O3" "O2/O3/O0" "O3/O0/O2" "O3/O2/O0")
    set(schedule "")
    foreach(cycle RANGE 1 ${cycles})
        foreach(block RANGE 1 6)
            math(EXPR index "(${block} - 1 + ${cycle} - 1) % 6")
            list(GET permutations ${index} order)
            string(REPLACE "/" ";" profiles "${order}")
            set(position 0)
            foreach(profile IN LISTS profiles)
                math(EXPR position "${position} + 1")
                list(APPEND schedule "${cycle},${block},${position},${profile}")
            endforeach()
        endforeach()
    endforeach()
    set(${result} "${schedule}" PARENT_SCOPE)
endfunction()

function(luna_validate_compiled_series_schedule schedule cycles)
    if(NOT cycles MATCHES "^[1-9][0-9]*$" OR cycles LESS 1 OR cycles GREATER 10)
        message(FATAL_ERROR "invalid compiled series cycles")
    endif()
    list(LENGTH schedule actual)
    math(EXPR expected "18 * ${cycles}")
    if(NOT actual EQUAL expected)
        message(FATAL_ERROR "compiled series schedule process count mismatch")
    endif()
    set(index 0)
    foreach(item IN LISTS schedule)
        if(NOT item MATCHES "^([1-9][0-9]*),([1-6]),([1-3]),(O[023])$")
            message(FATAL_ERROR "invalid compiled series schedule row: ${item}")
        endif()
        set(cycle ${CMAKE_MATCH_1})
        set(block ${CMAKE_MATCH_2})
        set(position ${CMAKE_MATCH_3})
        set(profile ${CMAKE_MATCH_4})
        math(EXPR wanted_cycle "${index} / 18 + 1")
        math(EXPR wanted_block "(${index} / 3) % 6 + 1")
        math(EXPR wanted_position "${index} % 3 + 1")
        if(NOT cycle EQUAL wanted_cycle OR NOT block EQUAL wanted_block OR NOT position EQUAL wanted_position OR
           DEFINED schedule_seen_${cycle}_${block}_${profile})
            message(FATAL_ERROR "compiled series schedule changed order or repeated a profile")
        endif()
        set(schedule_seen_${cycle}_${block}_${profile} TRUE)
        if(position EQUAL 1)
            set(order "${profile}")
        else()
            string(APPEND order "_${profile}")
            if(NOT DEFINED pair_${previous}_${profile})
                set(pair_${previous}_${profile} 0)
            endif()
            math(EXPR pair_${previous}_${profile} "${pair_${previous}_${profile}} + 1")
        endif()
        if(position EQUAL 3)
            if(DEFINED schedule_order_${cycle}_${order})
                message(FATAL_ERROR "compiled series schedule repeated a permutation")
            endif()
            set(schedule_order_${cycle}_${order} TRUE)
        endif()
        if(NOT DEFINED visit_${profile}_${position})
            set(visit_${profile}_${position} 0)
        endif()
        math(EXPR visit_${profile}_${position} "${visit_${profile}_${position}} + 1")
        set(previous ${profile})
        math(EXPR index "${index} + 1")
    endforeach()
    math(EXPR visits "2 * ${cycles}")
    foreach(profile IN ITEMS O0 O2 O3)
        foreach(position RANGE 1 3)
            if(NOT visit_${profile}_${position} EQUAL visits)
                message(FATAL_ERROR "compiled series schedule position imbalance")
            endif()
        endforeach()
        foreach(next IN ITEMS O0 O2 O3)
            if(NOT next STREQUAL profile AND NOT pair_${profile}_${next} EQUAL visits)
                message(FATAL_ERROR "compiled series schedule within-block pair imbalance")
            endif()
        endforeach()
    endforeach()
endfunction()

function(luna_compiled_series_identity output profile)
    # Compare per-profile keys separately, artifact/build facts across all runs.
    foreach(key IN ITEMS protocol git_commit probe_sha256 workload_sha256 build_type compiler cxx
            target data_layout host_container_sha256 plugin_container_sha256 orc_codegen
            candidate_count correctness_checks affinity timed_harness iterations)
        luna_compiled_probe_metadata("${output}" "${key}" value)
        if(DEFINED series_${key} AND NOT series_${key} STREQUAL value)
            message(FATAL_ERROR "compiled series changed common identity: ${key}")
        endif()
        set(series_${key} "${value}" PARENT_SCOPE)
    endforeach()
    luna_compiled_probe_metadata("${output}" materialization_key value)
    if(DEFINED series_key_${profile} AND NOT series_key_${profile} STREQUAL value)
        message(FATAL_ERROR "compiled series changed profile identity: ${profile}")
    endif()
    set(series_key_${profile} "${value}" PARENT_SCOPE)
endfunction()
