cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_probe_protocol.cmake")

# Read-only acceptance of an unpacked v1 bundle against this source checkout.
# No probe execution, extraction, writes, timing thresholds or release approval.
function(luna_bundle_digest value label)
    string(LENGTH "${value}" length)
    if(NOT length EQUAL 64 OR NOT value MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "bundle invalid SHA-256: ${label}")
    endif()
endfunction()

function(luna_bundle_read directory filename limit result digest)
    set(path "${directory}/${filename}")
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "bundle requires a regular non-symlink file: ${filename}")
    endif()
    get_filename_component(real "${path}" REALPATH)
    get_filename_component(parent "${real}" DIRECTORY)
    if(NOT parent STREQUAL directory)
        message(FATAL_ERROR "bundle file escaped directory: ${filename}")
    endif()
    file(SIZE "${path}" size)
    if(size LESS 1 OR size GREATER limit)
        message(FATAL_ERROR "bundle file exceeds size limit: ${filename}")
    endif()
    file(SHA256 "${path}" before)
    file(READ "${path}" content)
    file(SHA256 "${path}" after)
    # CMake text reads may normalize CRLF. Digest actual file bytes, not the
    # in-memory string, and require stable bytes on both sides of the read.
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "bundle file changed while reading: ${filename}")
    endif()
    if(content MATCHES ";")
        message(FATAL_ERROR "bundle does not allow semicolon list separators: ${filename}")
    endif()
    string(REPLACE "\r\n" "\n" content "${content}")
    set(${result} "${content}" PARENT_SCOPE)
    set(${digest} "${before}" PARENT_SCOPE)
endfunction()

function(luna_validate_compiled_bundle bundle_dir)
    luna_validate_compiled_bundle_impl("${bundle_dir}" uncontrolled)
endfunction()

# Trusted entry points select the mode, never an untrusted manifest or an
# ambient flag. The default entry point above remains uncontrolled-only.
function(luna_validate_compiled_bundle_impl bundle_dir mode)
    set(extra_keys "")
    if(mode STREQUAL "uncontrolled")
        set(expected_protocol luna.compiled-fragment-series.v1)
        set(expected_probe_protocol luna.compiled-fragment-cost.v2)
        set(runner_file compiled_fragment_series.cmake)
        set(anchor_prefix LUNA_COMPILED_BUNDLE)
    elseif(mode STREQUAL "pinned")
        set(expected_protocol luna.compiled-fragment-pinned-series.v1)
        set(expected_probe_protocol luna.compiled-fragment-cost.pinned-thread.v1)
        set(runner_file compiled_fragment_pinned_series.cmake)
        set(anchor_prefix LUNA_COMPILED_PINNED_BUNDLE)
        set(extra_keys logical_cpu processor_group affinity_control_sha256 setup_affinity pinned_protocol_validator_sha256)
    else()
        message(FATAL_ERROR "bundle unsupported reader mode")
    endif()
    if(NOT IS_DIRECTORY "${bundle_dir}" OR IS_SYMLINK "${bundle_dir}")
        message(FATAL_ERROR "bundle requires an existing non-symlink directory")
    endif()
    get_filename_component(directory "${bundle_dir}" REALPATH)
    luna_bundle_read("${directory}" manifest.csv 65536 manifest manifest_hash)
    if(DEFINED ${anchor_prefix}_EXPECTED_MANIFEST_SHA256)
        luna_bundle_digest("${${anchor_prefix}_EXPECTED_MANIFEST_SHA256}" expected_manifest)
        if(NOT manifest_hash STREQUAL "${${anchor_prefix}_EXPECTED_MANIFEST_SHA256}")
            message(FATAL_ERROR "bundle expected manifest SHA-256 mismatch")
        endif()
    endif()
    luna_compiled_probe_metadata("${manifest}" protocol manifest_protocol)
    luna_compiled_probe_metadata("${manifest}" probe_protocol manifest_probe_protocol)
    if(NOT manifest_protocol STREQUAL expected_protocol OR NOT manifest_probe_protocol STREQUAL expected_probe_protocol)
        message(FATAL_ERROR "bundle unsupported protocol")
    endif()
    set(keys protocol probe_protocol series_runner_sha256 protocol_validator_sha256
        git_commit probe_sha256 workload_sha256 build_type compiler cxx target data_layout
        host_container_sha256 plugin_container_sha256 orc_codegen affinity timed_harness iterations
        materialization_key_O0 materialization_key_O2 materialization_key_O3 cycles measured_processes
        verified_samples within_block_directed_pair_visits combined_sha256 ${extra_keys})
    foreach(key IN LISTS keys)
        luna_compiled_probe_metadata("${manifest}" "${key}" value)
        set(declared_${key} "${value}")
    endforeach()
    foreach(key IN ITEMS series_runner_sha256 protocol_validator_sha256 probe_sha256 workload_sha256
                         host_container_sha256 plugin_container_sha256 combined_sha256)
        luna_bundle_digest("${declared_${key}}" "${key}")
    endforeach()
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${runner_file}" runner_hash)
    file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/compiled_fragment_probe_protocol.cmake" validator_hash)
    if(NOT runner_hash STREQUAL declared_series_runner_sha256 OR
       NOT validator_hash STREQUAL declared_protocol_validator_sha256)
        message(FATAL_ERROR "bundle orchestration source SHA-256 mismatch; use matching source bytes")
    endif()
    if(mode STREQUAL "pinned")
        foreach(key IN ITEMS affinity_control_sha256 pinned_protocol_validator_sha256)
            luna_bundle_digest("${declared_${key}}" "${key}")
        endforeach()
        file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmarks/fragment_thread_affinity.h" control_hash)
        file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/compiled_fragment_pinned_protocol.cmake" pinned_validator_hash)
        if(NOT control_hash STREQUAL declared_affinity_control_sha256 OR
           NOT pinned_validator_hash STREQUAL declared_pinned_protocol_validator_sha256)
            message(FATAL_ERROR "pinned bundle controller/validator source SHA-256 mismatch")
        endif()
        if(NOT declared_logical_cpu MATCHES "^(0|[1-9][0-9]*)$" OR declared_logical_cpu GREATER 1023 OR
           NOT declared_processor_group MATCHES "^(0|none)$" OR
           (declared_processor_group STREQUAL "0" AND declared_logical_cpu GREATER 63))
            message(FATAL_ERROR "pinned bundle invalid CPU/group configuration")
        endif()
    endif()
    if(DEFINED ${anchor_prefix}_EXPECTED_COMMIT)
        string(LENGTH "${${anchor_prefix}_EXPECTED_COMMIT}" length)
        if(NOT length EQUAL 40 OR NOT "${${anchor_prefix}_EXPECTED_COMMIT}" MATCHES "^[0-9a-f]+$")
            message(FATAL_ERROR "bundle expected commit must be a full lowercase Git SHA-1")
        endif()
        if(NOT declared_git_commit STREQUAL "${${anchor_prefix}_EXPECTED_COMMIT}")
            message(FATAL_ERROR "bundle expected commit mismatch")
        endif()
    endif()
    if(NOT declared_cycles MATCHES "^([1-9][0-9]*),blocks_per_cycle=6$")
        message(FATAL_ERROR "bundle invalid cycle declaration")
    endif()
    set(cycles "${CMAKE_MATCH_1}")
    luna_compiled_series_schedule("${cycles}" expected_schedule)
    if(NOT declared_iterations MATCHES "^([1-9][0-9]*),warmup=[1-9][0-9]*,rounds=9$")
        message(FATAL_ERROR "bundle invalid iteration declaration")
    endif()
    set(iterations "${CMAKE_MATCH_1}")
    math(EXPR processes "${cycles} * 18")
    math(EXPR samples "${processes} * 81")
    math(EXPR visits "${cycles} * 2")
    if(NOT declared_measured_processes STREQUAL "${processes},fresh_process_per_record=yes" OR
       NOT declared_verified_samples STREQUAL "${samples},profile_position_visits=${visits}" OR
       NOT declared_within_block_directed_pair_visits STREQUAL "${visits},between_block_balance=unclaimed")
        message(FATAL_ERROR "bundle count/balance declaration mismatch")
    endif()
    set(combined "process,cycle,block,profile_position,profile,round,position,case,ns_per_op,calls,checksum\n")
    set(expected_files manifest.csv samples.csv)
    set(schedule "")
    set(index 0)
    set(headers 0)
    string(REPLACE "\n" ";" lines "${manifest}")
    foreach(line IN LISTS lines)
        if(line MATCHES "^# ([A-Za-z0-9_]+)=")
            if(NOT CMAKE_MATCH_1 IN_LIST keys)
                message(FATAL_ERROR "bundle unknown manifest metadata: ${CMAKE_MATCH_1}")
            endif()
        elseif(line STREQUAL "process,cycle,block,profile_position,profile,record,sha256")
            math(EXPR headers "${headers} + 1")
            if(NOT index EQUAL 0 OR NOT headers EQUAL 1)
                message(FATAL_ERROR "bundle manifest header misplaced or duplicated")
            endif()
        elseif(line MATCHES "^[0-9]")
            if(NOT headers EQUAL 1 OR index GREATER_EQUAL processes OR
               NOT line MATCHES "^([1-9][0-9]*),([1-9][0-9]*),([1-6]),([1-3]),(O[023]),(process-[1-9][0-9]*-O[023][.]csv),([0-9a-f]+)$")
                message(FATAL_ERROR "bundle malformed manifest row or record path: ${line}")
            endif()
            set(process "${CMAKE_MATCH_1}")
            set(cycle "${CMAKE_MATCH_2}")
            set(block "${CMAKE_MATCH_3}")
            set(position "${CMAKE_MATCH_4}")
            set(profile "${CMAKE_MATCH_5}")
            set(filename "${CMAKE_MATCH_6}")
            set(hash "${CMAKE_MATCH_7}")
            luna_bundle_digest("${hash}" "${filename}")
            math(EXPR wanted_process "${index} + 1")
            list(GET expected_schedule ${index} wanted_schedule)
            if(NOT process EQUAL wanted_process OR NOT filename STREQUAL "process-${process}-${profile}.csv" OR
               NOT "${cycle},${block},${position},${profile}" STREQUAL wanted_schedule)
                message(FATAL_ERROR "bundle manifest process/order mismatch")
            endif()
            list(APPEND schedule "${cycle},${block},${position},${profile}")
            list(APPEND expected_files "${filename}")
            luna_bundle_read("${directory}" "${filename}" 65536 record actual_hash)
            if(NOT actual_hash STREQUAL hash)
                message(FATAL_ERROR "bundle raw-file SHA-256 mismatch: ${filename}")
            endif()
            if(mode STREQUAL "pinned")
                luna_validate_compiled_pinned_probe("${record}" "${iterations}" "${profile}"
                    "${declared_logical_cpu}" "${declared_processor_group}")
                foreach(key IN ITEMS affinity_control_sha256 setup_affinity)
                    luna_compiled_probe_metadata("${record}" "${key}" value)
                    if(NOT declared_${key} STREQUAL value)
                        message(FATAL_ERROR "pinned bundle manifest/raw identity mismatch: ${key}")
                    endif()
                endforeach()
            else()
                luna_validate_compiled_probe("${record}" "${iterations}" "${profile}")
            endif()
            set(expected_hash_${filename} "${actual_hash}")
            foreach(key IN ITEMS git_commit probe_sha256 workload_sha256 build_type compiler cxx target data_layout
                    host_container_sha256 plugin_container_sha256 orc_codegen affinity timed_harness iterations)
                luna_compiled_probe_metadata("${record}" "${key}" value)
                if(NOT declared_${key} STREQUAL value)
                    message(FATAL_ERROR "bundle manifest/raw identity mismatch: ${key}")
                endif()
            endforeach()
            luna_compiled_probe_metadata("${record}" materialization_key value)
            if(NOT declared_materialization_key_${profile} STREQUAL value)
                message(FATAL_ERROR "bundle manifest/raw materialization key mismatch: ${profile}")
            endif()
            string(REPLACE "\n" ";" record_lines "${record}")
            foreach(sample IN LISTS record_lines)
                if(sample MATCHES "^[0-9]+,")
                    string(APPEND combined "${process},${cycle},${block},${position},${profile},${sample}\n")
                endif()
            endforeach()
            math(EXPR index "${index} + 1")
        elseif(NOT line STREQUAL "")
            message(FATAL_ERROR "bundle unexpected manifest text: ${line}")
        endif()
    endforeach()
    if(NOT index EQUAL processes OR NOT headers EQUAL 1)
        message(FATAL_ERROR "bundle manifest process count/header mismatch")
    endif()
    luna_validate_compiled_series_schedule("${schedule}" "${cycles}")
    luna_bundle_read("${directory}" samples.csv 4194304 written actual_hash)
    if(NOT actual_hash STREQUAL declared_combined_sha256)
        message(FATAL_ERROR "bundle combined SHA-256 mismatch")
    endif()
    if(NOT written STREQUAL combined)
        message(FATAL_ERROR "bundle combined rows do not match raw records")
    endif()
    set(expected_hash_samples.csv "${actual_hash}")
    file(GLOB actual_files RELATIVE "${directory}" "${directory}/*")
    list(SORT actual_files)
    list(SORT expected_files)
    if(NOT actual_files STREQUAL expected_files)
        message(FATAL_ERROR "bundle has unlisted directory entries")
    endif()
    foreach(filename IN LISTS expected_files)
        if(NOT filename STREQUAL "manifest.csv")
            if(IS_SYMLINK "${directory}/${filename}" OR IS_DIRECTORY "${directory}/${filename}")
                message(FATAL_ERROR "bundle file changed during validation: ${filename}")
            endif()
            file(SHA256 "${directory}/${filename}" final_hash)
            if(NOT final_hash STREQUAL expected_hash_${filename})
                message(FATAL_ERROR "bundle file changed during validation: ${filename}")
            endif()
        endif()
    endforeach()
    file(SHA256 "${directory}/manifest.csv" final_manifest_hash)
    if(NOT manifest_hash STREQUAL final_manifest_hash)
        message(FATAL_ERROR "bundle manifest changed during validation")
    endif()
    message(STATUS "Compiled Fragment ${mode} bundle: ${processes} records, ${samples} exact mapped samples; read-only integrity/protocol acceptance, not performance or release approval")
endfunction()

if(DEFINED LUNA_COMPILED_BUNDLE_DIR)
    luna_validate_compiled_bundle("${LUNA_COMPILED_BUNDLE_DIR}")
elseif(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    message(FATAL_ERROR "LUNA_COMPILED_BUNDLE_DIR is required")
endif()
