cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_pinned_protocol.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_pinned_fixture.cmake")


if(DEFINED TEST_CASE)
    luna_compiled_pinned_probe_fixture(O0 19 0 output)
    if(TEST_CASE STREQUAL wrong_controller)
        luna_compiled_probe_metadata("${output}" affinity_control_sha256 hash)
        string(REPEAT c 64 changed)
        string(REPLACE "${hash}" "${changed}" output "${output}")
    elseif(TEST_CASE STREQUAL duplicate_controller)
        string(APPEND output "# affinity_control_sha256=duplicate\n")
    elseif(TEST_CASE STREQUAL missing_controller)
        string(REGEX REPLACE "# affinity_control_sha256=[^\n]+\n" "" output "${output}")
    elseif(TEST_CASE STREQUAL wrong_cpu)
        string(REPLACE "logical_cpu=19" "logical_cpu=18" output "${output}")
    elseif(TEST_CASE STREQUAL wrong_group)
        string(REPLACE "processor_group=0" "processor_group=none" output "${output}")
    elseif(TEST_CASE STREQUAL wrong_scope)
        string(REPLACE "measurement_scope=dispatch_samples" "measurement_scope=all" output "${output}")
    elseif(TEST_CASE STREQUAL missing_setup)
        string(REPLACE "# setup_affinity=uncontrolled,measurement_scope=dispatch_samples\n" "" output "${output}")
    elseif(TEST_CASE STREQUAL wrong_checksum)
        string(REPLACE "1,1,plain,0.0,6,120" "1,1,plain,0.0,6,121" output "${output}")
    elseif(TEST_CASE STREQUAL invalid_cpu)
        luna_validate_compiled_pinned_probe("${output}" 3 O0 019 0)
    elseif(TEST_CASE STREQUAL invalid_group)
        luna_validate_compiled_pinned_probe("${output}" 3 O0 19 1)
    elseif(TEST_CASE STREQUAL windows_cpu_limit)
        luna_validate_compiled_pinned_probe("${output}" 3 O0 64 0)
    elseif(TEST_CASE STREQUAL linux_cpu_limit)
        luna_validate_compiled_pinned_probe("${output}" 3 O0 1024 none)
    elseif(TEST_CASE STREQUAL default_reader_rejects_pinned)
        luna_validate_compiled_probe("${output}" 3 O0)
    elseif(TEST_CASE STREQUAL pinned_reader_rejects_default)
        luna_compiled_probe_fixture(O0 output)
    else()
        message(FATAL_ERROR "unknown pinned protocol case")
    endif()
    luna_validate_compiled_pinned_probe("${output}" 3 O0 19 0)
    message(FATAL_ERROR "invalid pinned fixture was accepted")
endif()

# Synthetic only: no OS affinity changes, timing processes or observation writes.
foreach(profile IN ITEMS O0 O2 O3)
    foreach(specification IN ITEMS "0|0" "19|0" "1023|none")
        string(REPLACE "|" ";" fields "${specification}")
        list(GET fields 0 cpu)
        list(GET fields 1 group)
        luna_compiled_pinned_probe_fixture("${profile}" "${cpu}" "${group}" output)
        luna_validate_compiled_pinned_probe("${output}" 3 "${profile}" "${cpu}" "${group}")
        string(REPLACE "\n" "\r\n" crlf "${output}")
        luna_validate_compiled_pinned_probe("${crlf}" 3 "${profile}" "${cpu}" "${group}")
    endforeach()
endforeach()
set(warning_option -Werror=dev)
if(CMAKE_VERSION VERSION_GREATER_EQUAL 4.4)
    set(warning_option -Werror=author)
endif()
foreach(test IN ITEMS "wrong_controller|metadata mismatch" "duplicate_controller|exactly once"
        "missing_controller|exactly once" "wrong_cpu|metadata mismatch" "wrong_group|metadata mismatch"
        "wrong_scope|metadata mismatch" "missing_setup|exactly once" "wrong_checksum|checksum mismatch"
        "invalid_cpu|validation configuration" "invalid_group|validation configuration"
        "windows_cpu_limit|validation configuration" "linux_cpu_limit|validation configuration"
        "default_reader_rejects_pinned|metadata mismatch" "pinned_reader_rejects_default|metadata mismatch")
    string(REPLACE "|" ";" fields "${test}")
    list(GET fields 0 name)
    list(GET fields 1 expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "${warning_option}"
            "-DTEST_CASE=${name}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT status EQUAL 1 OR NOT output STREQUAL "" OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "pinned protocol rejection failed: ${name}: ${status}: ${output}${errors}")
    endif()
endforeach()
message(STATUS "Compiled pinned protocol: synthetic LF/CRLF metadata/sample validation and strict mode separation; no timing")
