cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/../tests/compiled_fragment_bundle.cmake")

# Known v1 inventory shared by export and read-only byte verification. It is
# validation input, not a complete compiler/build source snapshot.
function(luna_compiled_evidence_inventory cycles result)
    set(paths bundle/manifest.csv bundle/samples.csv)
    luna_compiled_series_schedule("${cycles}" schedule)
    set(index 0)
    foreach(item IN LISTS schedule)
        math(EXPR index "${index} + 1")
        string(REGEX REPLACE "^.*," "" profile "${item}")
        list(APPEND paths "bundle/process-${index}-${profile}.csv")
    endforeach()
    foreach(path IN ITEMS tests/compiled_fragment_bundle.cmake tests/compiled_fragment_probe_protocol.cmake
            tests/compiled_fragment_series.cmake tools/compiled_fragment_evidence.cmake
            tools/package_compiled_fragment_evidence.cmake benchmarks/compiled_fragment_benchmark.cpp
            benchmarks/compiled_fragment/host/luna.package benchmarks/compiled_fragment/host/src/effects.luna
            benchmarks/compiled_fragment/luna.lock benchmarks/compiled_fragment/luna.workspace
            benchmarks/compiled_fragment/plugin/luna.package benchmarks/compiled_fragment/plugin/src/effects.luna)
        list(APPEND paths "source/${path}")
    endforeach()
    list(SORT paths)
    set(${result} "${paths}" PARENT_SCOPE)
endfunction()

function(luna_compiled_evidence_file root relative result)
    set(path "${root}/${relative}")
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "evidence requires a non-symlink file: ${relative}")
    endif()
    get_filename_component(real "${path}" REALPATH)
    if(NOT real STREQUAL path)
        message(FATAL_ERROR "evidence file has a redirected parent: ${relative}")
    endif()
    file(SIZE "${path}" size)
    if(size LESS 1 OR size GREATER 4194304)
        message(FATAL_ERROR "evidence file outside size limit: ${relative}")
    endif()
    file(SHA256 "${path}" hash)
    set(${result} "${hash}" PARENT_SCOPE)
endfunction()

# Only checksum/layout acceptance; never includes or executes archived code.
function(luna_verify_compiled_evidence evidence_dir)
    if(NOT IS_DIRECTORY "${evidence_dir}" OR IS_SYMLINK "${evidence_dir}")
        message(FATAL_ERROR "evidence requires a non-symlink directory")
    endif()
    get_filename_component(root "${evidence_dir}" REALPATH)
    luna_bundle_read("${root}" evidence.csv 65536 index index_hash)
    if(DEFINED LUNA_COMPILED_EVIDENCE_EXPECTED_INDEX_SHA256)
        luna_bundle_digest("${LUNA_COMPILED_EVIDENCE_EXPECTED_INDEX_SHA256}" expected_index)
        if(NOT index_hash STREQUAL LUNA_COMPILED_EVIDENCE_EXPECTED_INDEX_SHA256)
            message(FATAL_ERROR "evidence expected index SHA-256 mismatch")
        endif()
    endif()
    set(keys protocol bundle_protocol bundle_git_commit bundle_manifest_sha256 cycles source_snapshot approval)
    foreach(key IN LISTS keys)
        luna_compiled_probe_metadata("${index}" "${key}" value)
        set(declared_${key} "${value}")
    endforeach()
    if(NOT declared_protocol STREQUAL "luna.compiled-fragment-evidence.v1" OR
       NOT declared_bundle_protocol STREQUAL "luna.compiled-fragment-series.v1" OR
       NOT declared_source_snapshot STREQUAL "validation-inputs-only" OR NOT declared_approval STREQUAL "none")
        message(FATAL_ERROR "evidence unsupported protocol or approval claim")
    endif()
    string(LENGTH "${declared_bundle_git_commit}" length)
    if(NOT length EQUAL 40 OR NOT declared_bundle_git_commit MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "evidence requires a full lowercase commit")
    endif()
    if(DEFINED LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT AND
       NOT declared_bundle_git_commit STREQUAL LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT)
        message(FATAL_ERROR "evidence expected commit mismatch")
    endif()
    luna_bundle_digest("${declared_bundle_manifest_sha256}" bundle_manifest)
    luna_compiled_evidence_inventory("${declared_cycles}" paths)
    list(LENGTH paths count)
    set(seen 0)
    set(headers 0)
    string(REPLACE "\n" ";" lines "${index}")
    foreach(line IN LISTS lines)
        if(line MATCHES "^# ([A-Za-z0-9_]+)=")
            if(NOT CMAKE_MATCH_1 IN_LIST keys)
                message(FATAL_ERROR "evidence unknown metadata")
            endif()
        elseif(line STREQUAL "path,sha256")
            math(EXPR headers "${headers} + 1")
            if(NOT headers EQUAL 1 OR NOT seen EQUAL 0)
                message(FATAL_ERROR "evidence duplicated/misplaced header")
            endif()
        elseif(NOT line STREQUAL "")
            if(NOT headers EQUAL 1 OR seen GREATER_EQUAL count OR
               NOT line MATCHES "^([a-zA-Z0-9_./-]+),([0-9a-f]+)$")
                message(FATAL_ERROR "evidence invalid checksum row")
            endif()
            set(relative "${CMAKE_MATCH_1}")
            set(hash "${CMAKE_MATCH_2}")
            list(GET paths ${seen} expected)
            if(NOT relative STREQUAL expected)
                message(FATAL_ERROR "evidence noncanonical path or inventory order")
            endif()
            luna_bundle_digest("${hash}" "${relative}")
            luna_compiled_evidence_file("${root}" "${relative}" actual)
            if(NOT actual STREQUAL hash)
                message(FATAL_ERROR "evidence file SHA-256 mismatch: ${relative}")
            endif()
            if(relative STREQUAL "bundle/manifest.csv" AND NOT hash STREQUAL declared_bundle_manifest_sha256)
                message(FATAL_ERROR "evidence bundle manifest anchor mismatch")
            endif()
            math(EXPR seen "${seen} + 1")
        endif()
    endforeach()
    if(NOT seen EQUAL count OR NOT headers EQUAL 1)
        message(FATAL_ERROR "evidence inventory count/header mismatch")
    endif()
    luna_bundle_read("${root}/bundle" manifest.csv 65536 manifest manifest_hash)
    foreach(pair IN ITEMS "git_commit|${declared_bundle_git_commit}" "protocol|${declared_bundle_protocol}"
                          "cycles|${declared_cycles},blocks_per_cycle=6")
        string(REPLACE "|" ";" fields "${pair}")
        list(GET fields 0 key)
        list(GET fields 1 expected)
        luna_compiled_probe_metadata("${manifest}" "${key}" value)
        if(NOT value STREQUAL expected)
            message(FATAL_ERROR "evidence bundle metadata anchor mismatch: ${key}")
        endif()
    endforeach()
    if(NOT manifest_hash STREQUAL declared_bundle_manifest_sha256)
        message(FATAL_ERROR "evidence manifest changed during byte verification")
    endif()
    set(expected_entries evidence.csv ${paths})
    foreach(path IN LISTS paths)
        get_filename_component(parent "${path}" DIRECTORY)
        while(NOT parent STREQUAL "")
            if(IS_SYMLINK "${root}/${parent}")
                message(FATAL_ERROR "evidence symlink directory")
            endif()
            list(APPEND expected_entries "${parent}")
            get_filename_component(parent "${parent}" DIRECTORY)
        endwhile()
    endforeach()
    list(REMOVE_DUPLICATES expected_entries)
    list(SORT expected_entries)
    file(GLOB_RECURSE actual_entries LIST_DIRECTORIES TRUE RELATIVE "${root}" "${root}/*")
    list(SORT actual_entries)
    if(NOT actual_entries STREQUAL expected_entries)
        message(FATAL_ERROR "evidence has unlisted entries")
    endif()
    file(SHA256 "${root}/evidence.csv" final_hash)
    if(NOT final_hash STREQUAL index_hash)
        message(FATAL_ERROR "evidence index changed during validation")
    endif()
    message(STATUS "Compiled Fragment evidence: ${count} file byte hashes; no archived code executed, no protocol/performance/release approval")
endfunction()

if(DEFINED LUNA_COMPILED_EVIDENCE_DIR)
    luna_verify_compiled_evidence("${LUNA_COMPILED_EVIDENCE_DIR}")
elseif(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    message(FATAL_ERROR "LUNA_COMPILED_EVIDENCE_DIR is required")
endif()
