#!/usr/bin/env python3
"""Generate deterministic CPU benchmark sources for the Luna/C++23 comparison.

Every Luna workload and its C++23 counterpart must execute bit-identical
arithmetic over bit-identical input data. This generator emits the shared
input arrays from one seeded RNG, so both sides cannot drift apart.

The generated `.luna` sources are committed as static benchmark inputs; this
script exists only to make the data provenance auditable:

    python3 tools/gen_cpu_bench_sources.py

Only writes files under benchmarks/ that are part of the extended CPU suite.
"""
import random

SEED = 0x5EED
MASK = 2_147_483_647  # keep all values in positive i32 range


def literal(values, per_line=12, indent="    "):
    """Render a Luna/C++ array literal from a list of ints."""
    chunks = [", ".join(str(v) for v in values[i:i + per_line])
              for i in range(0, len(values), per_line)]
    sep = ",\n" + indent
    return indent + sep.join(chunks)


def luna_source(header_comment, body):
    return (f"// Deterministic workload for the extended CPU comparison suite.\n"
            f"// Generated by tools/gen_cpu_bench_sources.py (seed={SEED}).\n"
            + header_comment +
            f"fn main() -> i32 {{\n{body}\n}}\n")


def write_luna(path, source):
    with open(path, "w") as fh:
        fh.write(source)
    print(f"wrote {path}")


def cpp_literal(values, per_line=12):
    chunks = [", ".join(str(v) for v in values[i:i + per_line])
              for i in range(0, len(values), per_line)]
    return ",\n        ".join(chunks)


def write_cpp_suite(array4096, array4096b, perm64, sort64, keys128):
    a = cpp_literal(array4096)
    b = cpp_literal(array4096b)
    p = cpp_literal(perm64)
    s = cpp_literal(sort64)
    k = cpp_literal(keys128)

    source = f"""// Extended CPU comparison suite: the 9 original workloads plus 11 new
// dimensions. Arithmetic and input data are bit-identical to the Luna
// counterparts in luna_cpu_*.luna (generated by tools/gen_cpu_bench_sources.py,
// seed={SEED}). Never edit the input arrays by hand; regenerate instead.

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

// Defined in a separate translation unit so an ordinary non-LTO benchmark
// build cannot fold the allocation/deallocation pair into scalar arithmetic.
extern "C" void* luna_benchmark_allocate(std::size_t size);
extern "C" void luna_benchmark_deallocate(void* pointer);

namespace {{
constexpr int kIterations = 20'000'000;
constexpr int kAllocations = 500'000;

constexpr std::uint32_t kArray4096[4096] = {{
        {a}
}};
constexpr std::uint32_t kArray4096b[4096] = {{
        {b}
}};
constexpr std::uint32_t kPerm64[64] = {{
        {p}
}};
constexpr std::uint32_t kSort64[64] = {{
        {s}
}};
constexpr std::uint32_t kKeys128[128] = {{
        {k}
}};

std::uint32_t mix(std::uint32_t value) {{
    return (value * 1'664'525u + 1'013'904'223u) & 2'147'483'647u;
}}

std::uint32_t arithmetic() {{
    std::uint32_t value = 1;
    for (int i = 0; i < kIterations; ++i) value = mix(value);
    return value & 255u;
}}

std::uint32_t branchy() {{
    std::int32_t value = 1;
    for (int i = 0; i < kIterations; ++i) {{
        if ((value & 1) == 0) value /= 2;
        else value = (value * 3 + 1) % 1'000'003;
    }}
    return static_cast<std::uint32_t>(value) & 255u;
}}

inline std::uint32_t step(std::uint32_t value) {{
    return (value * 5u + 7u) & 2'147'483'647u;
}}

std::uint32_t calls() {{
    std::uint32_t value = 1;
    for (int i = 0; i < kIterations; ++i) value = step(value);
    return value & 255u;
}}

std::uint32_t safe_array_reference() {{
    std::array<std::int32_t, 8> values{{1, 2, 3, 4, 5, 6, 7, 8}};
    for (int i = 0; i < kIterations; ++i) {{
        const int index = i & 7;
        values[static_cast<std::size_t>(index)] += i & 31;
    }}
    std::int32_t total = 0;
    for (const auto value : values) total += value;
    return static_cast<std::uint32_t>(total) & 255u;
}}

std::uint32_t allocation() {{
    std::int32_t checksum = 0;
    for (int i = 0; i < kAllocations; ++i) {{
        auto* item = static_cast<std::int32_t*>(
            luna_benchmark_allocate(sizeof(std::int32_t)));
        *item = i;
        checksum = (checksum + i) % 1'000'003;
        luna_benchmark_deallocate(item);
    }}
    return static_cast<std::uint32_t>(checksum) & 255u;
}}

std::uint32_t bitmix() {{
    std::uint32_t value = 305'419'896u;
    for (int i = 0; i < kIterations; ++i) {{
        value = (value ^ (value << 13)) & 2'147'483'647u;
        value ^= value >> 17;
        value ^= value << 5;
        value &= 2'147'483'647u;
    }}
    return value & 255u;
}}

std::uint32_t reduction() {{
    std::uint32_t first = 1;
    std::uint32_t second = 3;
    std::uint32_t third = 5;
    std::uint32_t fourth = 7;
    for (int i = 0; i < 10'000'000; ++i) {{
        const auto value = static_cast<std::uint32_t>(i);
        first = (first * 33u + (value & 255u)) & 2'147'483'647u;
        second = (second * 65u + ((value * 3u) & 255u)) & 2'147'483'647u;
        third = (third * 129u + ((value * 5u) & 255u)) & 2'147'483'647u;
        fourth = (fourth * 257u + ((value * 7u) & 255u)) & 2'147'483'647u;
    }}
    return (first + second + third + fourth) & 255u;
}}

std::uint32_t array_scan() {{
    std::array<std::int32_t, 64> values{{}};
    for (std::size_t i = 0; i < values.size(); ++i) {{
        values[i] = static_cast<std::int32_t>(i + 1);
    }}
    std::int32_t state = 1;
    for (int i = 0; i < kIterations; ++i) {{
        const auto index = static_cast<std::size_t>(i & 63);
        const auto next = (static_cast<std::uint32_t>(values[index]) +
                           static_cast<std::uint32_t>(state) +
                           (static_cast<std::uint32_t>(i) & 31u)) &
                          2'147'483'647u;
        values[index] = static_cast<std::int32_t>(next);
        state = static_cast<std::int32_t>(
            (static_cast<std::uint32_t>(state) + next) & 2'147'483'647u);
    }}
    return static_cast<std::uint32_t>(state) & 255u;
}}

std::uint32_t nested() {{
    std::uint32_t state = 1;
    for (int row = 0; row < 2'500; ++row) {{
        for (int column = 0; column < 4'000; ++column) {{
            state = (state * 33u + static_cast<std::uint32_t>(row) +
                     static_cast<std::uint32_t>(column)) &
                    2'147'483'647u;
        }}
    }}
    return state & 255u;
}}

// ---- new dimensions (mirror luna_cpu_*.luna exactly) ----

std::uint32_t divmod() {{
    std::uint32_t value = 1;
    for (int i = 0; i < kIterations; ++i) {{
        value = (value * 998'244'353u) & 2'147'483'647u;
        const std::uint32_t q = value / 977u;
        const std::uint32_t r = value % 991u;
        value = (q + r * 1'000'003u) & 2'147'483'647u;
    }}
    return value & 255u;
}}

std::uint32_t chase() {{
    std::uint32_t index = 17;
    std::uint32_t sum = 0;
    for (int i = 0; i < kIterations; ++i) {{
        index = kPerm64[index];
        sum += index;
    }}
    return sum & 255u;
}}

std::uint32_t stream_read() {{
    std::uint32_t sum = 0;
    for (int pass = 0; pass < 2441; ++pass) {{
        for (std::size_t j = 0; j < 4096; ++j) {{
            sum += kArray4096[j];
        }}
    }}
    return sum & 255u;
}}

std::uint32_t stream_write() {{
    std::array<std::uint32_t, 4096> data{{}};
    std::memcpy(data.data(), kArray4096, sizeof(kArray4096));
    for (int pass = 0; pass < 2441; ++pass) {{
        for (std::size_t j = 0; j < 4096; ++j) {{
            data[j] = (static_cast<std::uint32_t>(pass * 4096 + static_cast<int>(j)) *
                       2'654'435'761u) &
                      2'147'483'647u;
        }}
    }}
    std::uint32_t sum = 0;
    for (const auto value : data) sum += value;
    return sum & 255u;
}}

std::uint32_t stream_copy() {{
    std::array<std::uint32_t, 4096> target{{}};
    std::memcpy(target.data(), kArray4096b, sizeof(kArray4096b));
    for (int pass = 0; pass < 2441; ++pass) {{
        for (std::size_t j = 0; j < 4096; ++j) {{
            target[j] = kArray4096[j];
        }}
    }}
    std::uint32_t sum = 0;
    for (const auto value : target) sum += value;
    return sum & 255u;
}}

std::uint32_t saxpy() {{
    std::array<std::uint32_t, 4096> data{{}};
    std::memcpy(data.data(), kArray4096, sizeof(kArray4096));
    for (int pass = 0; pass < 2441; ++pass) {{
        for (std::size_t j = 0; j < 4096; ++j) {{
            data[j] = (data[j] * 3u + 1u) & 2'147'483'647u;
        }}
    }}
    std::uint32_t sum = 0;
    for (const auto value : data) sum += value;
    return sum & 255u;
}}

std::uint32_t sort() {{
    std::array<std::uint32_t, 64> work{{}};
    std::uint32_t checksum = 0;
    for (int round = 0; round < 100'000; ++round) {{
        for (std::size_t c = 0; c < 64; ++c) work[c] = kSort64[c];
        for (int p = 1; p < 64; ++p) {{
            const auto key = work[static_cast<std::size_t>(p)];
            int q = p - 1;
            while (q >= 0 && work[static_cast<std::size_t>(q)] > key) {{
                work[static_cast<std::size_t>(q + 1)] =
                    work[static_cast<std::size_t>(q)];
                --q;
            }}
            work[static_cast<std::size_t>(q + 1)] = key;
        }}
        for (std::size_t s = 0; s < 64; ++s) {{
            checksum = (checksum + work[s]) & 2'147'483'647u;
        }}
    }}
    return checksum & 255u;
}}

std::uint32_t hash() {{
    std::array<std::uint32_t, 256> slots{{}};
    slots.fill(2'147'483'647u);
    for (std::size_t i = 0; i < 128; ++i) {{
        const auto key = kKeys128[i];
        auto bucket = key & 255u;
        while (slots[bucket] != 2'147'483'647u) {{
            bucket = (bucket + 1u) & 255u;
        }}
        slots[bucket] = key;
    }}
    std::uint32_t checksum = 0;
    for (int probe = 0; probe < 100'000; ++probe) {{
        const auto key = kKeys128[static_cast<std::size_t>(probe) & 127u];
        auto bucket = key & 255u;
        while (slots[bucket] != key) {{
            bucket = (bucket + 1u) & 255u;
        }}
        checksum = (checksum + bucket) & 2'147'483'647u;
    }}
    return checksum & 255u;
}}

std::uint32_t find() {{
    const auto target = kArray4096[2047u];
    std::uint32_t checksum = 0;
    for (int search = 0; search < 200'000; ++search) {{
        std::size_t pos = 0;
        while (pos < 4096 && kArray4096[pos] != target) ++pos;
        checksum = (checksum + static_cast<std::uint32_t>(pos)) & 2'147'483'647u;
    }}
    return checksum & 255u;
}}

std::uint32_t fib_rec(std::uint32_t n) {{
    if (n < 2) return n;
    return fib_rec(n - 1) + fib_rec(n - 2);
}}

std::uint32_t recursion() {{
    return fib_rec(32) & 255u;
}}

std::uint32_t rotate() {{
    std::uint32_t value = 305'419'896u;
    std::uint32_t sum = 0;
    for (int i = 0; i < kIterations; ++i) {{
        const auto mixed = value ^ static_cast<std::uint32_t>(i);
        value = (mixed << 7) | (mixed >> 25);
        value &= 2'147'483'647u;
        std::uint32_t bits = 0;
        for (int b = 0; b < 32; ++b) {{
            bits += (value >> static_cast<unsigned>(b)) & 1u;
        }}
        sum += bits;
    }}
    return sum & 255u;
}}
}} // namespace

int main(int argc, char** argv) {{
    if (argc != 2) return 2;
    std::uint32_t result = 0;
    if (std::strcmp(argv[1], "arithmetic") == 0) result = arithmetic();
    else if (std::strcmp(argv[1], "branch") == 0) result = branchy();
    else if (std::strcmp(argv[1], "calls") == 0) result = calls();
    else if (std::strcmp(argv[1], "array") == 0) result = safe_array_reference();
    else if (std::strcmp(argv[1], "allocation") == 0) result = allocation();
    else if (std::strcmp(argv[1], "bitmix") == 0) result = bitmix();
    else if (std::strcmp(argv[1], "reduction") == 0) result = reduction();
    else if (std::strcmp(argv[1], "array-scan") == 0) result = array_scan();
    else if (std::strcmp(argv[1], "nested") == 0) result = nested();
    else if (std::strcmp(argv[1], "divmod") == 0) result = divmod();
    else if (std::strcmp(argv[1], "chase") == 0) result = chase();
    else if (std::strcmp(argv[1], "stream-read") == 0) result = stream_read();
    else if (std::strcmp(argv[1], "stream-write") == 0) result = stream_write();
    else if (std::strcmp(argv[1], "stream-copy") == 0) result = stream_copy();
    else if (std::strcmp(argv[1], "saxpy") == 0) result = saxpy();
    else if (std::strcmp(argv[1], "sort") == 0) result = sort();
    else if (std::strcmp(argv[1], "hash") == 0) result = hash();
    else if (std::strcmp(argv[1], "find") == 0) result = find();
    else if (std::strcmp(argv[1], "recursion") == 0) result = recursion();
    else if (std::strcmp(argv[1], "rotate") == 0) result = rotate();
    else return 2;
    std::printf("%u\\n", result);
    return 0;
}}
"""
    with open("benchmarks/cpp23_cpu_suite_extended.cpp", "w") as fh:
        fh.write(source)
    print("wrote benchmarks/cpp23_cpu_suite_extended.cpp")


def main():
    rng = random.Random(SEED)
    array4096 = [rng.randrange(0, MASK + 1) for _ in range(4096)]
    array4096b = [rng.randrange(0, MASK + 1) for _ in range(4096)]
    perm64 = list(range(64))
    rng.shuffle(perm64)
    sort64 = [rng.randrange(0, 1_000_003) for _ in range(64)]
    keys128 = rng.sample(range(1024), 128)

    a4096 = literal(array4096)
    a4096b = literal(array4096b)
    p64 = literal(perm64)
    s64 = literal(sort64)
    k128 = literal(keys128)
    empty256 = literal([2_147_483_647] * 256)

    # ---- divmod: integer division/modulo latency ----
    body = """    let value: i32 = 1;
    let i: i32 = 0;
    while i < 20000000 {
        value = (value * 998244353) & 2147483647;
        let q = value / 977;
        let r = value % 991;
        value = (q + r * 1000003) & 2147483647;
        i += 1;
    }
    print(value & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_divmod.luna", luna_source("", body))

    # ---- chase: permutation-based pointer chasing (latency bound) ----
    body = f"""    let next: array<i32, 64> = [
{p64}
    ];
    let index: i32 = 17;
    let sum: i32 = 0;
    let i: i32 = 0;
    while i < 20000000 {{
        index = next[index];
        sum += index;
        i += 1;
    }}
    print(sum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_chase.luna", luna_source("", body))

    # ---- stream-read: sequential 16 KiB read ----
    body = f"""    let data: array<i32, 4096> = [
{a4096}
    ];
    let sum: i32 = 0;
    let pass: i32 = 0;
    while pass < 2441 {{
        let j: i32 = 0;
        while j < 4096 {{
            sum += data[j];
            j += 1;
        }}
        pass += 1;
    }}
    print(sum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_stream_read.luna", luna_source("", body))

    # ---- stream-write: sequential 16 KiB write ----
    body = f"""    let data: array<i32, 4096> = [
{a4096}
    ];
    let pass: i32 = 0;
    while pass < 2441 {{
        let j: i32 = 0;
        while j < 4096 {{
            data[j] = ((pass * 4096 + j) * 2654435761) & 2147483647;
            j += 1;
        }}
        pass += 1;
    }}
    let sum: i32 = 0;
    let j: i32 = 0;
    while j < 4096 {{
        sum += data[j];
        j += 1;
    }}
    print(sum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_stream_write.luna", luna_source("", body))

    # ---- stream-copy: read 16 KiB, write 16 KiB ----
    body = f"""    let source: array<i32, 4096> = [
{a4096}
    ];
    let target: array<i32, 4096> = [
{a4096b}
    ];
    let pass: i32 = 0;
    while pass < 2441 {{
        let j: i32 = 0;
        while j < 4096 {{
            target[j] = source[j];
            j += 1;
        }}
        pass += 1;
    }}
    let sum: i32 = 0;
    let j: i32 = 0;
    while j < 4096 {{
        sum += target[j];
        j += 1;
    }}
    print(sum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_stream_copy.luna", luna_source("", body))

    # ---- saxpy: in-place vectorizable v*3+1 over 16 KiB ----
    body = f"""    let data: array<i32, 4096> = [
{a4096}
    ];
    let pass: i32 = 0;
    while pass < 2441 {{
        let j: i32 = 0;
        while j < 4096 {{
            data[j] = (data[j] * 3 + 1) & 2147483647;
            j += 1;
        }}
        pass += 1;
    }}
    let sum: i32 = 0;
    let j: i32 = 0;
    while j < 4096 {{
        sum += data[j];
        j += 1;
    }}
    print(sum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_saxpy.luna", luna_source("", body))

    # ---- sort: repeated insertion sort of a 64-element copy ----
    body = f"""    let source: array<i32, 64> = [
{s64}
    ];
    let work: array<i32, 64> = [
{s64}
    ];
    let checksum: i32 = 0;
    let round: i32 = 0;
    while round < 100000 {{
        let c: i32 = 0;
        while c < 64 {{
            work[c] = source[c];
            c += 1;
        }}
        let p: i32 = 1;
        while p < 64 {{
            let key = work[p];
            let q = p - 1;
            while q >= 0 && work[q] > key {{
                work[q + 1] = work[q];
                q -= 1;
            }}
            work[q + 1] = key;
            p += 1;
        }}
        let s: i32 = 0;
        while s < 64 {{
            checksum = (checksum + work[s]) & 2147483647;
            s += 1;
        }}
        round += 1;
    }}
    print(checksum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_sort.luna", luna_source("", body))

    # ---- hash: open-addressing table, 128 inserts + 100k lookups ----
    body = f"""    let keys: array<i32, 128> = [
{k128}
    ];
    // 2147483647 marks an empty slot; keys stay in 0..1023.
    let slots: array<i32, 256> = [
{empty256}
    ];
    let i: i32 = 0;
    while i < 128 {{
        let key = keys[i];
        let bucket = key & 255;
        while slots[bucket] != 2147483647 {{
            bucket = (bucket + 1) & 255;
        }}
        slots[bucket] = key;
        i += 1;
    }}
    let checksum: i32 = 0;
    let probe: i32 = 0;
    while probe < 100000 {{
        let key = keys[probe & 127];
        let bucket = key & 255;
        while slots[bucket] != key {{
            bucket = (bucket + 1) & 255;
        }}
        checksum = (checksum + bucket) & 2147483647;
        probe += 1;
    }}
    print(checksum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_hash.luna", luna_source("", body))

    # ---- find: scan 16 KiB for a known target, 200k searches ----
    body = f"""    let data: array<i32, 4096> = [
{a4096}
    ];
    let target = data[2047];
    let checksum: i32 = 0;
    let search: i32 = 0;
    while search < 200000 {{
        let pos: i32 = 0;
        while pos < 4096 && data[pos] != target {{
            pos += 1;
        }}
        checksum = (checksum + pos) & 2147483647;
        search += 1;
    }}
    print(checksum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_find.luna", luna_source("", body))

    # ---- recursion: fib(32) ----
    rec = """fn fib(n: i32) -> i32 {
    if n < 2 {
        return n;
    }
    return fib(n - 1) + fib(n - 2);
}

fn main() -> i32 {
    print(fib(32) & 255);
    return 0;
    return 0;
}
"""
    write_luna("benchmarks/luna_cpu_recursion.luna",
               f"// Deterministic workload for the extended CPU comparison suite.\n"
               f"// Generated by tools/gen_cpu_bench_sources.py (seed={SEED}).\n{rec}")

    # ---- rotate: manual bit rotate + manual popcount, 20M ----
    body = """    let value: i32 = 305419896;
    let sum: i32 = 0;
    let i: i32 = 0;
    while i < 20000000 {
        value = ((value ^ i) << 7) | ((value ^ i) >> 25);
        value = value & 2147483647;
        let bits: i32 = 0;
        let b: i32 = 0;
        while b < 32 {
            bits += (value >> b) & 1;
            b += 1;
        }
        sum += bits;
        i += 1;
    }
    print(sum & 255);
    return 0;"""
    write_luna("benchmarks/luna_cpu_rotate.luna", luna_source("", body))

    write_cpp_suite(array4096, array4096b, perm64, sort64, keys128)


if __name__ == "__main__":
    main()
