#!/usr/bin/env python3
"""Generate heterogeneous-compute scale benchmark sources for Luna.

Luna device buffers are the only indexable large-memory surface, so the
memory-bandwidth scaling story lives here: sizes sweep 8 MiB .. 1 GiB, plus
compute-intensity (1x/4x/16x ALU per element per pass), transfer-roundtrip and
launch-overhead microbenchmarks. Sources are generated per size because the
device allocation count is a source literal in the current ABI.

Usage:
    python3 tools/gen_heterogeneous_scale.py <output-dir> [--sizes ...] [--ops ...]

The C++23/HIP counterpart takes the same parameters from argv
(benchmarks/cpp23_hip_vector.cpp), so both sides always execute the identical
element count, pass count, op count and transfer sequence.
"""
import argparse
import os
import sys

VECTOR_TEMPLATE = """// Generated by tools/gen_heterogeneous_scale.py: {elements} elements
// ({miB} MiB), {passes} passes, {ops}x ops per element per pass.
kernel fn initialize(index: i32, data: &mut device_buffer<i32>) {{
    gpu_store_i32(data, index, index);
}}

kernel fn transform(index: i32, data: &mut device_buffer<i32>) {{
    let v = gpu_load_i32(data, index);
{ops_body}
    gpu_store_i32(data, index, v);
}}

fn main() -> i32 {{
    linear let data = gpu_alloc_i32({elements});

    let init = launch initialize[threads: {elements}](borrow mut data);
    await init;

    let step1 = launch transform[threads: {elements}](borrow mut data);
    await step1;
    let step2 = launch transform[threads: {elements}](borrow mut data);
    await step2;
    let step3 = launch transform[threads: {elements}](borrow mut data);
    await step3;
    let step4 = launch transform[threads: {elements}](borrow mut data);
    await step4;
    let step5 = launch transform[threads: {elements}](borrow mut data);
    await step5;
    let step6 = launch transform[threads: {elements}](borrow mut data);
    await step6;
    let step7 = launch transform[threads: {elements}](borrow mut data);
    await step7;
    let step8 = launch transform[threads: {elements}](borrow mut data);
    await step8;
    let step9 = launch transform[threads: {elements}](borrow mut data);
    await step9;
    let step10 = launch transform[threads: {elements}](borrow mut data);
    await step10;

    let checksum = gpu_load_i32(borrow data, 0);
    print(checksum);
    gpu_free(move data);
    return 0;
}}
"""

TRANSFER_TEMPLATE = """// Generated by tools/gen_heterogeneous_scale.py: host<->device roundtrip,
// {elements} elements ({miB} MiB). The host buffer is calloc zero-filled;
// the roundtrip must leave element 0 at 0 on both sides.
extern "C" fn calloc(count: usize, size: usize) -> raw<i32>;
extern "C" fn c_free(linear pointer: raw<i32>) as "free";

fn main() -> i32 {{
    linear let host = calloc({elements}, 4);
    linear let data = gpu_alloc_i32({elements});

    gpu_copy_from_host_i32(borrow mut data, borrow host, {elements});
    gpu_copy_to_host_i32(borrow mut host, borrow data, {elements});

    let result = gpu_load_i32(borrow data, 0);
    gpu_free(move data);
    c_free(move host);
    print(result);
    return 0;
}}
"""

LAUNCH_TEMPLATE = """// Generated by tools/gen_heterogeneous_scale.py: {launches} sequential
// launch/await pairs on an 8-thread kernel. Isolates per-launch host
// overhead (module already loaded) from kernel execution.
kernel fn touch(index: i32, data: &mut device_buffer<i32>) {{
    let v = gpu_load_i32(data, index);
    gpu_store_i32(data, index, v + 1);
}}

fn main() -> i32 {{
    linear let data = gpu_alloc_i32(8);
    gpu_store_i32(borrow mut data, 0, 41);

    let i: i32 = 0;
    while i < {launches} {{
        let done = launch touch[threads: 8](borrow mut data);
        await done;
        i += 1;
    }}

    print(gpu_load_i32(borrow data, 0));
    gpu_free(move data);
    return 0;
}}
"""


def ops_body(ops):
    lines = []
    for step in range(ops):
        suffix = "" if step == 0 else f"  // pass {step + 1}"
        lines.append(f"    v = v * 3 + 1;{suffix}")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("out_dir")
    parser.add_argument("--sizes", nargs="+", type=int,
                        default=[8, 16, 32, 64, 128, 256, 512, 1024])
    parser.add_argument("--ops", nargs="+", type=int, default=[1, 4, 16])
    parser.add_argument("--launches", type=int, default=1000)
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    written = 0

    for mi_b in args.sizes:
        elements = mi_b * 1024 * 1024 // 4
        for ops in args.ops:
            path = os.path.join(args.out_dir, f"vector_{mi_b}MiB_ops{ops}.luna")
            with open(path, "w") as fh:
                fh.write(VECTOR_TEMPLATE.format(
                    elements=elements, miB=mi_b, passes=10, ops=ops,
                    ops_body=ops_body(ops)))
            written += 1

        path = os.path.join(args.out_dir, f"transfer_{mi_b}MiB.luna")
        with open(path, "w") as fh:
            fh.write(TRANSFER_TEMPLATE.format(elements=elements, miB=mi_b))
        written += 1

    path = os.path.join(args.out_dir, f"launch_{args.launches}.luna")
    with open(path, "w") as fh:
        fh.write(LAUNCH_TEMPLATE.format(launches=args.launches))
    written += 1

    print(f"wrote {written} sources to {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
