cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/compiled_fragment_evidence.cmake")

function(luna_package_compiled_evidence)
    foreach(key IN ITEMS BUNDLE_DIR OUTPUT_DIR EXPECTED_COMMIT EXPECTED_MANIFEST_SHA256)
        if(NOT DEFINED LUNA_COMPILED_EVIDENCE_${key} OR LUNA_COMPILED_EVIDENCE_${key} STREQUAL "")
            message(FATAL_ERROR "evidence export requires ${key}")
        endif()
    endforeach()
    get_filename_component(requested "${LUNA_COMPILED_EVIDENCE_OUTPUT_DIR}" ABSOLUTE)
    get_filename_component(parent "${requested}" DIRECTORY)
    get_filename_component(name "${requested}" NAME)
    if(NOT IS_DIRECTORY "${parent}" OR IS_SYMLINK "${parent}")
        message(FATAL_ERROR "evidence export requires an existing non-symlink output parent")
    endif()
    get_filename_component(parent "${parent}" REALPATH)
    set(output "${parent}/${name}")
    if(EXISTS "${output}" OR IS_SYMLINK "${output}")
        message(FATAL_ERROR "evidence export output already exists; never overwritten")
    endif()
    get_filename_component(bundle "${LUNA_COMPILED_EVIDENCE_BUNDLE_DIR}" REALPATH)
    set(boundary "${bundle}/")
    set(candidate "${output}/")
    if(WIN32)
        string(TOLOWER "${boundary}" boundary)
        string(TOLOWER "${candidate}" candidate)
    endif()
    string(FIND "${candidate}" "${boundary}" nested)
    if(nested EQUAL 0)
        message(FATAL_ERROR "evidence output must not be inside the input bundle")
    endif()
    set(LUNA_COMPILED_BUNDLE_EXPECTED_COMMIT "${LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT}")
    set(LUNA_COMPILED_BUNDLE_EXPECTED_MANIFEST_SHA256 "${LUNA_COMPILED_EVIDENCE_EXPECTED_MANIFEST_SHA256}")
    luna_validate_compiled_bundle("${LUNA_COMPILED_EVIDENCE_BUNDLE_DIR}")
    luna_bundle_read("${bundle}" manifest.csv 65536 manifest manifest_hash)
    luna_compiled_probe_metadata("${manifest}" cycles configuration)
    string(REGEX REPLACE ",.*$" "" cycles "${configuration}")
    luna_compiled_evidence_inventory("${cycles}" paths)
    get_filename_component(source_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." REALPATH)
    set(index "# protocol=luna.compiled-fragment-evidence.v1\n# bundle_protocol=luna.compiled-fragment-series.v1\n")
    string(APPEND index "# bundle_git_commit=${LUNA_COMPILED_EVIDENCE_EXPECTED_COMMIT}\n")
    string(APPEND index "# bundle_manifest_sha256=${manifest_hash}\n# cycles=${cycles}\n")
    string(APPEND index "# source_snapshot=validation-inputs-only\n# approval=none\npath,sha256\n")
    # Capture input byte hashes before creating output. Every path comes from
    # the closed v1 inventory; neither user paths nor archived code are loaded.
    foreach(path IN LISTS paths)
        if(path MATCHES "^bundle/(.+)$")
            set(input_root "${bundle}")
            set(relative "${CMAKE_MATCH_1}")
        elseif(path MATCHES "^source/(.+)$")
            set(input_root "${source_root}")
            set(relative "${CMAKE_MATCH_1}")
        endif()
        set(input "${input_root}/${relative}")
        luna_compiled_evidence_file("${input_root}" "${relative}" hash)
        set(input_${path} "${input}")
        set(hash_${path} "${hash}")
        string(APPEND index "${path},${hash}\n")
    endforeach()
    if(EXISTS "${output}" OR IS_SYMLINK "${output}")
        message(FATAL_ERROR "evidence output appeared during validation")
    endif()
    foreach(path IN LISTS paths)
        set(destination "${output}/${path}")
        if(EXISTS "${destination}" OR IS_SYMLINK "${destination}")
            message(FATAL_ERROR "evidence destination appeared during export")
        endif()
        get_filename_component(destination_parent "${destination}" DIRECTORY)
        file(MAKE_DIRECTORY "${destination_parent}")
        configure_file("${input_${path}}" "${destination}" COPYONLY)
        file(SHA256 "${input_${path}}" after)
        file(SHA256 "${destination}" copied)
        if(NOT hash_${path} STREQUAL after OR NOT after STREQUAL copied)
            message(FATAL_ERROR "evidence input or copied bytes changed: ${path}")
        endif()
    endforeach()
    # Recheck the whole observation input. An interrupted export may leave a
    # partial directory; evidence.csv is written last, never used as a signature.
    luna_validate_compiled_bundle("${bundle}")
    foreach(path IN LISTS paths)
        file(SHA256 "${input_${path}}" after)
        file(SHA256 "${output}/${path}" copied)
        if(NOT hash_${path} STREQUAL after OR NOT after STREQUAL copied)
            message(FATAL_ERROR "evidence bytes changed before index publication: ${path}")
        endif()
    endforeach()
    file(WRITE "${output}/evidence.csv" "${index}")
    luna_verify_compiled_evidence("${output}")
    file(SHA256 "${output}/evidence.csv" anchor)
    message(STATUS "Evidence export complete: ${output}; index SHA-256=${anchor}; retention/storage must be arranged separately")
endfunction()

if(DEFINED LUNA_COMPILED_EVIDENCE_OUTPUT_DIR OR CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    luna_package_compiled_evidence()
endif()
